---
title: "IOTC statistical data reporting: Form ROS-LL (v`r BASE_VERSION`)"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  word_document2:
    reference_docx: "../../templates/doc_template.docx"
    number_sections: FALSE
    reference_num: TRUE
    fig_caption: TRUE

  html_document2:
    css: "../../templates/html_template.css"
    includes: 
      in_header: "../../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
---

# Description

This form provides for the reporting of operational and catch data from longline fisheries under the IOTC Regional Observer Scheme (ROS). The form is designed to capture verified information on fishing activity, catch composition, and bycatch associated with longline operations, including IOTC species, and other bycatch species.The reporting format follows the standards adopted by the IOTC Scientific Committee and includes multiple hierarchical data levels, ranging from trip and set information to species-specific catch and bycatch records. Data collected through this form contribute to scientific assessments of tuna and tuna-like species and support monitoring of the impact of longline fisheries on associated and dependent species.Observers are required to complete the form for longline operations covered by the ROS, ensuring consistency, transparency, and quality of the data collected.

REPLACE WITH PROPER FORM LINK Click [here](./Form-1RC.xlsx) to download a blank version of Form 1RC, or [return](./index.html) to the list of all IOTC statistical data reporting forms.

# Data Content

Vessel and trip identifiers; effort and gear characteristics (hooks, soak time, set position); operational details of each set; catch and bycatch by species in number and weight; fate of catch (retained/discarded); interactions with sharks, seabirds, turtles, and other species; and mitigation measures used. Data are stratified by year, fleet, fishery, and IOTC main area.

# Metadata

## Submission Information

Fill out focal point information (full name, email, finalization date, and submission date) Fill out organization information (name, email)

## General Information

| Element | Requirement | Description | Format | Input value |
|:-----------|:-------------:|:--------------|:-------------:|:-------------:|
| Reporting year | M | Gregorian calendar year of the fishing activities reported through the dataset | Integer | e.g.,1996 |
| Reporting entity | M |Three-letter (alpha-3) code of the entity reporting the dataset to the IOTC Secretariat  |String  | **Code_iso3** from Entities |
| Reporting flag / Chartering state | M | The reporting flag or chartering state **OR** 	Three-letter (alpha-3) code of the country registration of the fishing vessels  | String | **Code_iso3** from Countries |
| Data source | M | The source of data provided (Observer data or EM DATA) |  |  |

# (O-INFO) Observer and Observed Trip Information

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID | M | The trip unique identifier. This should begin with the observation or trip start date (YYYY-MM-DD), followed by, IOTC observer number, IOTC vessel identifier as per RAV (Register of Active Vessels) and vessel main gear code as per IOTC classification. |  | e.g. 2024-01-23/IOTCFRA001/IOTC012345/LL |

## Observer Identification

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| IOTC ID | M | Alphanumeric registration number allocated by the IOTC Secretariat |  | e.g. IOTC_0976 |
| Full name | M | The name of the scientific observer(s) that collected the data on-board the fishing vessel or EM reviewer | Free entry. Plain text | e.g. John Doe |

## Observer Trip Details

| **Embarkation:** The starting port. If the first observation is available after the departure form the port while the vessel is within port limits, this is still recorded as the observation starting port. If the observation starts at sea outside port limits (onboard observer boarding the vessel via a vessel transfer or EM records not available at the trip starting date due to a recording failure) , record “at sea”.

::: {style="margin-left:40px"}
| **In port**
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The country or EEZ of the observation starting location |  **Code_iso3 from ....** |e.g., FRA |
| Port code | O | The port of the observation starting location  | **CODE_ISO from ...** | e.g., RE REU |
:::

::: {style="margin-left:40px"}
| **At sea**
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Latitude | O | The latitude of the observation starting location. | dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
| Longitude | O | The longitude of the observation starting location. | dd°mm,m’ N/S | e.g., 55.53 - CORRECT FORMAT? |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Data/time UTC | O | The date and time of the start of observations | YYYY-MM-DDThh:mm | e.g., 1/7/2023  12:00:00 AM
:::

| **Disembarkation:** The ending port. If the last observation is available after a port launch while the vessel is within port limits, this is still recorded as the observation ending port. If the observation ends at sea outside port limits (onboard observer disembarking the vessel via a vessel transfer or EM records not available at the end of observations due to a recording failure) , record “at sea”
| 

::: {style="margin-left:40px"}
| **In port**
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The country or EEZ of the observation ending location | **Code_iso3 from ....** | e.g., FRA | 
| Port code | O | The port of the observation ending location | **CODE_ISO from ...** | e.g., RE REU |
:::

::: {style="margin-left:40px"}
| **At sea**
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Latitude | O | The latitude of the observation ending location. | dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
| Longitude | O | The longitude of the observation ending location. | dd°mm,m’ N/S | e.g., 55.53 - CORRECT FORMAT? |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Data/time UTC | O | The date and time of the end of observations | YYYY-MM-DDThh:mm  |e.g., 1/7/2023  12:00:00 AM
:::

## Observed Trip Summary

| **Number of fishing events:** Insert description here

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| conducted | M | The total number of fishing events/sets conducted by the vessel from the observation starting date to the observation ending date, regardless their catch and data collection activities. | Integer |  |
| observed | M | The total number of fishing sets/events monitored by the observer. In the case of EM, only processed events to be included | Integer | |
:::

| **Number of days:** Insert description here

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Searching | O | Number of hours/days searching during the observation period | Integer |  |
| Actively fishing | O | Number of active fishing hours/days during the observation period | Integer |  |
| In fishing area | O | Number of hours in the fishing area during the observation period | Integer |  |
| Transiting | O | Number of hours transiting during the observation period | Integer | |
| Lost | O | Number of hours/days lost during the observation period | Integer | |
:::

| **Reasons for lost days:** Insert description here

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Reason codes | O | Reason(s) of hours lost | **Code** from Reasons for Days Lost | e.g., AW |
:::

# (V-INFO) Vessel \> General Information

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |

## Vessel Information

| Identification: Insert description here, maybe explain guidelines or why we need vessel identification

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Name | M | The vessel full name as recorded on vessel official documentation or record the vessel full name as imprinted on the vessel itself or EM records | Plain text | e.g., CAP EST |
| Flag or chartering code | M | The name of country in which vessel is registered. Where chartering occurs, record name of the chartering country | **Code from LINK TO CODE!!** | e.g., FRA |
| IOTC number | M | Vessel IOTC number as per the IOTC Record of Authorized Vessels and crosschecked with the number recorded on vessel certificates. | Free entry, alphanumeric code | e.g., IOTC008460 |
| IMO number | O | The vessel IMO number | seven-digit number | e.g.,  |
| International radio call sign (IRCS) | O | Vessel radio call sign if available. This is the number displayed prominently on the vessel’s side or superstructure | Alphanumeric code |  |
:::

| Registration: Insert description or explanation here

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The code of vessel's country of registry |  **Code_iso3 from ....** | e.g., FRA | 
| Port code | O | The code of vessel's port of registry (also called home port) shown on its registration documents and lettered on the stern of the ship's hull – also include the country. |  **CODE_ISO from ...** | e.g., RE REU |
| Reg number | O | The number issued by country in which the vessel is registered, shown on its registration documents and written on the hull of the vessel. This may be a combination of characters and numbers; record them all  | Alphanumeric or numeric code according to CPC standards | e.g., CBG303 |
:::

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Licensed target species | O | Licensed target species (FAO spp. 3-alpha code) as specified in vessel licences or permit conditions. Vessels will generally target a narrow range or aggregation of species, however one or more might not be an IOTC species; record them all. |**CODE** from TARGET SPECIES CODE |e.g.,   |
| Main Fishing Gear) | M | Vessel main fishing gear | **CODE** from |e.g.,  DL |

| Vessel Personnel: insert description here

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Fishing master | M | The fishing master name and nationality in full | Full name: Plain text ; Nationality code: Three-letter (alpha-3) code (ISO 3166) | e.g., John Doe, FRA |
| Skipper/captain | M | Skipper name and nationality in full | Full name: Plain text ; Nationality code: Three-letter (alpha-3) code (ISO 3166) | e.g. John Doe, FRA |
| Crew number | O | The number of crew. This should be cross checked against the vessel's crew list | Integer |  |
:::

# (V-TRIP) Vessel \> Trip details

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |

## Trip Details

| Vessel departure: The name and/or geographical coordinates of the port from where the vessel sailed – also include the country. If the vessel started a new trip at sea following transshipment record ‘at-sea’ plus the geographical coordinates corresponding to the location the trip started

::: {style="margin-left:40px"}
| In port
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The country or EEZ of the observation starting location. |  **Code_iso3 from ....** | e.g., FRA | 
| Port code | O | The port of the observation starting location | **CODE_ISO from ...** | e.g., RE REU |
| Latitude | O | The latitude of the observation starting location. | dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
| Longitude | O | The longitude of the observation starting location |dd°mm,m’ N/S | eg., **55.53** - CORRECT FORMAT?  |
:::

::: {style="margin-left:40px"}
|               |     |     |            |                  |
|:--------------|:---:|:----|:----------:|:----------------:|
| Date/time UTC |  O  |     |YYYY-MM-DDThh:mm  |e.g., 1/7/2023  12:00:00 AM |
:::

::: {style="margin-left:40px"}
| At sea
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The country or EEZ of the observation starting location. | **Code_iso3 from ....** | e.g., FRA | 
| Latitude | O | The latitude of the observation starting location. |  dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
| Longitude | O | The longitude of the observation starting location | dd°mm,m’ N/S | eg., **55.53** - CORRECT FORMAT?  |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date/time UTC | O | The date and time the vessel departed from port or from a transshipment location | YYYY-MM-DDThh:mm  |e.g., 1/7/2023  12:00:00 AM |
:::

| Vessel return: The name and/or geographical coordinates of the port where the vessel returned – also include the country. If the vessel arrived at a transshipment location record ‘at-sea’ plus the geographical coordinates corresponding to the location the transshipment started. If the observer disembarked before the vessel returned then record expected port of return as provided by the vessel

::: {style="margin-left:40px"}
| In port
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The country or EEZ of the observation ending location. |**Code_iso3 from ....** | e.g., FRA | 
| Port code | O | The port of the observation ending location |**CODE_ISO from ...** | e.g., RE REU |
| Latitude | O | The latitude of the observation ending location. | dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
| Longitude | O | The longitude of the observation ending location | dd°mm,m’ N/S |eg., **55.53** - CORRECT FORMAT?  |
:::

::: {style="margin-left:40px"}
|               |     |     |                             |     |
|:--------------|:---:|:----|:---------------------------:|:---:|
| Date/time UTC |  O  |     | YYYY-MM-DDThh:mm |  e.g., 1/7/2023  12:00:00 AM |
:::

::: {style="margin-left:40px"}
| At sea
:::

::: {style="margin-left:80px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Country code | O | The country or EEZ of the observation ending location. | **Code_iso3 from ....** | e.g., FRA | 
| Latitude | O | The latitude of the observation ending location. | dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
| Longitude | O | The longitude of the observation ending location | dd°mm,m’ N/S | eg., **55.53** - CORRECT FORMAT?  |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date/time UTC | O | The date and time the fishing vessel finishes its fishing campaign. i.e. returns to port or to a transshipment location for unloading. If the observer disembarks before the vessel returns then record expected date and time of arrival (ETA) as provided by the vessel | YYYY-MM-DDThh:mm |  e.g., 1/7/2023  12:00:00 AM |
:::

# (V-ATTRIBUTES) Vessel \> Vessel Attributes

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |

## Vessel Attributes

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Tonnage (GT) | O | The vessel tonnage as specified in vessel registration documents | Float |  |
| Length (M) | O | The vessel overall length (LOA) as specified in vessel registration documents | Floats |  |
| Hull material code | O | The vessel hull material | Two letters code |  |
| Main engines | O | The make (brand) and power of the main engines |  |  |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Make | O |  | Free entry. Plain text |  |
| Power value | O |  | Float |  |
| KW/HP/BHP | O |  | Power units code (KW, HP, or BHP) |  |
:::

|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Fish storage capacity | O | The vessel total maximum capacity to store catches. This should include blast freezer(s) capacity. Note: specify units (metric Tons (mT.) or cubic meters (m3)) - from original ROS description form\*\* | Float |  |
| Fish preservation methods | O | Fish preservation methods: Record the method(s) used by the vessel to preserve the catch (e.g. iced, frozen in brine, deep-frozen) | **Code** from Fish Preservation Methods | e.g., BR  |
| Fish storage types | O | The type of structure(s) present on-board used by the vessel to store the catch | **Code** from Types of Fish Storage |e.g., BF  |


| Autonomy range: Vessel autonomy, expressed by the time (days) a vessel can spend at sea without refuelling. If this information is not available then record vessel range expressed in cruising distance (nautical miles). If a figure for the range cannot be obtained, the observer should calculate vessel range as follows.

\<Vessel range (nm)\> = \<Vessel average cruising distance per metric ton (nm/mT)\> : \<Tonnage of fuel carried (mT)\> Note: specify units( days or nautical miles)" **- original ROS description form**

::: {style="margin-left:40px"}
| Element | Requirement | Description |      Format       | Input value |
|:--------|:-----------:|:------------|:-----------------:|:-----------:|
| Value   |      O      |             |       Float       |             |
| Days/NM |      O      |             | Select DAYS or NM |             |
:::

## Vessel Electronics

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| GPS | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| VMS | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| AIS | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| Radars | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| Track Plotter | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| Depth sounder | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| Sonar | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| Doppler current meter | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| XBT | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| VHF radios | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| HF radios | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| Satellite comms | O | Indicate Yes if on board No if not sighted. | Yes/No |  |
| FIS | O | Indicate Yes of No if the vessel has access to a Fisheries Information service | Yes/No |  |

## Waste Management

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Waste category | O | The category of the waste produced by the vessel | **Code** from Waste Category | e.g., CP |
| Storage/disposal method | O | How the waste was disposed of | **Code** from |e.g., AS |

# (G-GENERAL) Longline General Gear Specifications

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |

## Special Equipment or Machinery

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Line shooter | M | Indicate Yes if vessel equipped with this technology | Yes/No |  |
| Line hauler | M | Indicate Yes if vessel equipped with this technology | Yes/No |  |
| Bait casting machine | M | Indicate Yes if vessel equipped with this technology | Yes/No |  |

# (G-CONFIG-BRANCHLINES) Longline General Gear Specifications \> Branchline Configurations

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |

## Branchline Configurations

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Configuration number | O | Unique number for a specific branchline specification as detailed based on the fields below | Integer |  |
| Section number | O |  | Integer |  |
| Material type code | O | The branchline material for each of the four sections where section 1 is that closest to the mainline and section 4 is the leader; note that wire trace may be sheathed by a plastic or nylon coating | **Code** from Material Type Code | e.g., NL |
| Length (M) | O | Length of the branchline for each of the four sections where section 1 is that closest to the mainline and section 4 is the leader | Float |  |
| Diameter (cm) | O | Length of the branchline for each of the four sections where section 1 is that closest to the mainline and section 4 is the leader | Float |  |

## Additional Branchline Details

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Storage codes | O | If the branch lines are coiled up and packed into baskets (BSK), or layered out in tubs (TBS), or coiled up onto reels (RLS) | **Code** from ___ | e.g.,  |
|  |  |  |  |  |
|  |  |  |  |  |
|  |  |  |  |  |

# (G-CONFIG-MITIGATION-DEVICES) Longline Gear Specifications \> Mitigation Devices

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |

## Tori Line Details

Note: If the vessel was equipped with a tori line, provide tori line details below. If not tori line was present on board, fill in NA for not applicable. \_ from original ROS description form\*\*

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Tori line length | M | The total length of the tori line (not including streamers) | Float |  |
| Streamer type code | M | The type of streamers which are used with the tori line (e.g. paired or single) | **Code** from ____ | e.g.,  |
| Reach surface | O | Yes if the streamers are long enough to touch the surface of the water in calm conditions or No if they are not | Yes/No |  |
| Streamer line length (max) | M | Length of individual streamer lines (minimum and maximum where lengths vary). Record only one length if they do not vary | Float |  |
| Streamer line length (min) | O | Length of individual streamer lines (minimum and maximum where lengths vary). Record only one length if they do not vary | Float |  |
| No. streamers per line | M | The number of streamers that are attached to a single tori line | Integer |  |
| Distance between streamers | O | The distance between streamers | Float |  |
| Attached height | M | The height that the tori line is attached above the water level | Float |  |
| Towed objects | O | The total number and type of towed objects used to maintain tori line tension and achieve aerial extent when deployed | Number: integer; Type: Free entry. Plain text |  |

## Other Mitigation Devices

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Device codes | O |  | **Code** from _____ | e.g., |

# (E-SET) Longline Fishing Events \> Setting Operations

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | This should be a four digit numerical code beginning 0001. Set numbers should be consecutive from the start of the first line set to the last line set of the observed trip | 4 digits number |  |

## Setting Operations

| Element       | Requirement | Description | Format | Input value |
|:--------------|:-----------:|:------------|:------:|:-----------:|
| Start setting |             |             |        |             |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC the first dhan buoy and / or radio buoy is deployed to start the setting of the line |YYYY-MM-DDThh:mm |  e.g., 1/7/2023  12:00:00 AM |
| Position | M | The position in latitude and longitude for the start of the setting operation |  dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  |
:::

| End setting

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC that the last dhan buoy and / or radio buoy is deployed. | YYYY-MM-DDThh:mm |  e.g., 1/7/2023  12:00:00 AM |
| Position | M | The position in latitude and longitude for the end of the setting operation | dd°mm,m’ N/S | eg., **-20.88** - CORRECT FORMAT?  | |
:::

|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Vessel speed | M | The vessel’s average speed during setting (knots) | Float |  |
| Line setter speed | M | The speed setting of the line setter (meters/second) | Float |  |
| Mainline: Mainline material and total set length (i.e. the total deployed length of the mainline for the specific set). Usually calculated by multiplying the total time to set the line and the average line setter speed, taking into account any interruption times. This information can be obtained from the Fishing Master and cross checked against observer calculations |  |  |  |  |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Material code | O |  | **Code** from ____ | e.g.,|
| value | O |  | Float |  |
| KM/NM | O |  | Indicate unit (KM or NM) |  |
:::

| Clip on time

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Branchline | O | The average time interval in seconds between the “beeps” that indicate to the crew to clip on a branch line. | Yes/No |  |
| Buoys | O | The average time interval in seconds between the “beeps” that indicate to the crew to clip on a buoy | Yes/No |  |
:::

|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Number of total hooks set | M | The total number of hooks deployed for the set. Usually calculated by multiplying number of baskets by the average number of hooks between the baskets. This information can be obtained from the Fishing Master and cross checked against observer calculations | Integer |  |
| Number of total floats on set | O | The total number of floats deployed during the set (this should not include the radio/dhan buoys). Usually calculated by subtracting the number of buoys in their holders before setting by the number of buoys in their holders after setting. This information can be obtained from the Fishing Master and cross checked against observer calculations | Integer |  |
| Number of hooks between floats | M | The number of hooks set between floats. This will correspond to the number of hooks stored in each basket/tub, or on a reel and will be equivalent to the number of branch lines set. | Integer |  |
| Shark lines |  |  |  |  |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Set | M | Indicate Yes or No if shark lines were set during the operation | Yes/No |  |
| Number of lines | O | The number of shark lines set during the operation. If no shark lines are set then record zero (0) | Integer |  |
:::

| leader material

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Material code | M | Each leader type used in the set (based on Table T16 – line material types) | **Code** from ___ | e.g., |
| Percentage | M | for each leader type used in the set, estimate the percentage of total branchlines in the set using that leader type. Estimate by counting the number of branchlines in a basket by leader type and dividing each count by the total hooks in the basket. This assumes uniform use of leader types across baskets in a set. Estimates should be adjusted if there is variation across baskets (within a set) in leader proportions | Float |  |
:::

| Branchline length max: specify the minimum and maximum total branchline lengths observed in the set. Total branchline length is measured (in meters) from the mainline clip to the hook. If total branchline lengths are uniform across the set, write the same number in the minimum and maximum fields

::: {style="margin-left:40px"}
| Element | Requirement | Description |         Format          | Input value |
|:--------|:-----------:|:------------|:-----------------------:|:-----------:|
| Value   |      M      |             |          Float          |             |
| CM/M    |      M      |             | Indicate Unit (CM or M) |             |
:::

|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Target species | M | The target species for the set (FAO spp. 3-alpha code) | **Code** from Target species | e.g., |

# (E-SET-LIGHTS) Longline Fishing Events \> Setting Operations \> Attached Lights

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |

## Attached Lights

| Attached lights: Number of lights attached to the branchlines per type and colour

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type code | M |  | **Code** from  | e.g., CL |
| Colour code | M |  | **Code** from  | e.g.,  YL|
| Number of lights | M |  | Integer |  |
:::

# (E-SET-MITIGATION-MEASURES)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |

## Mitigation Measures

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Number of tori lines deployed | M | The total number of tori lines deployed during the setting operation. Record zero if none were deployed | Integer |  |
| Minimum deck lighting used | M | Indicate Y or No for whether minimum deck lighting is used during night setting. Mitigation measures of IOTC Res 23/07 | **Integer** shouldn't this be Yes/No??? |  |
| Hooks set between dusk dawn | M |  | Integer |  |
| Branchline weighted | O | Indicate Yes or No or Unknown (UNK) if the branch line is weighted. CPCs adjustment using additional information | Yes/No/Unk |  |
| Average branchline weight (g) | M | The average weight of weights or sinkers attached to the branchlines (weights deployed on the snood prior to setting) | Float |  |
| Percent branchline weighted | M | The proportion of branchlines weighted (%). If all weighted, record 100% | Float |  |
| Hook sinker distance (cm) | M | The distance of the weights/sinkers from the eye of the hook | Float |  |
| Hook pods | M | Indicate Yes or No if the bait is protected on the branchlines until they are a certain depth below the surface | Yes/No |  |

#### ALERT: check reporting format for the minimum deck lighting used

## Branchline Details

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Configuration number | O | The number of branchlines set by type (branchline configuration number). Branchline types must be in accordance to types previously defined under the “Gear specifications” section. | Alphanumeric code |  |
| Number of branchlines set | O | The number of branchlines set by type (branchline configuration number). Branchline types must be in accordance to types previously defined under the “Gear specifications” section. | Integer |  |

## Other Mitigation Measures Used

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Measure codes | M | Any other mitigation measures observed | **Code** from  | e.g.,|

# (E-SET-HOOKS)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |

## Setting Operations \> Hook Details \> Hook

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Types codes | M | The types of hooks used | **Code** from  |  |
| Percentage | O | The percentage (%) of hooks set by type | Float |  |
| Variations | O | Where possible indicate any variations in hook type, hook material, and presence/absence of hook ring | Free entry. Plain text. |  |

# (E-SET-BAITS)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |

## Setting Operations \> Bait Details \> Bait

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Condition code | M | Bait type/condition used | **Code** from  |  |
| Species code | M | The species/species group of bait used (FAO spp. 3-alpha code) | **Code** from  |  |
| Percentage | M | The approximate proportion of bait species and condition used across all hooks in the set (%) | Float |  |
| Dye colour | O | The colour or colours that the different baits are dyed (e.g. blue to avoid bird bycatch). If none, write NONE | Free entry. Plain text. |  |

# (E-SET-HAULING)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |

## Hauling Operations

| Element       | Requirement | Description | Format | Input value |
|:--------------|:-----------:|:------------|:------:|:-----------:|
| Start hauling |             |             |        |             |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC when the first dhan buoy and / or radio buoy is hauled back on-board to start hauling the line. | YYYY-MM-DDThh:mm  |  |
| Position | M | The position in latitude and longitude for the start of the hauling operation | dd°mm,m’ N/S |  |
:::

| End hauling

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | M | The date and the time when the when the last component of the longline gear (dhan buoy and / or radio buoy) is hauled back on-board | YYYY-MM-DDThh:mm  |  |
| Position | M | The position in latitude and longitude for the end of the hauling operation | dd°mm,m’ N/S |  |
:::

|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Offal management | O | Fate given to the offal (fish heads, guts, etc.) and bait produced during the observed set. Indicate if these are retained for batch disposal (BD) at a later stage and/or disposed of ad hoc (AH) as they accumulate | **Code** from | e.g., |
| Position of offal disposal - position code | O | The position where offal and used bait was disposed. Indicate if these are disposed at port side (BB), starboard (SB) or aft (AF) | \*\*MISSING CODES- DEFINE |  |
| Bird scaring device at hauler | M | Yes if a bird scaring device was deployed during hauling operations and No if not. | Yes/No |  |
| Number of branchline haulings observed | M | The number of branchline haulings observed | Integer |  |
| Number of hooks retrieved during observation | M | The number of hooks retrieved during observation | Integer |  |
| Sampling protocol code | M | Sampling protocol followed by the observer | **CODE** from | e.g., |

# (E-SET-HAULING-BITEOFFS)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |

## Biteoff Details - Branchline

| Element | Requirement | Description | Format | Input value |
|:--------|:-----------:|:------------|:------:|:-----------:|

Biteoff details - branchline: For each branchline configuration setup previously identified how many have had the hook bitten off. This only includes bite-offs observed while the observer was in a position to observe and record the hooks coming directly out of the water - from original ROS description form \*\*

::: {style="margin-left:40px"}
| Element              | Requirement | Description | Format  | Input value |
|:---------------------|:-----------:|:------------|:-------:|:-----------:|
| Configuration number |      O      |             | Integer |             |
| Number of biteoffs   |      O      |             | Integer |             |
:::

# (E-SET-CATCHES)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID | M | refer to parent observed trip |  |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |
| Catch ID | M | Unique within a specific set, as a branch of set-ID | Alphanumeric code |  |

## Catch Details

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Species code | M | The species code for each specimen observed using FAO three figure alpha codes. If species FAO code is not available, record the species scientific name | **Code** from ___ | e.g., |
| Fate (type and code) | M | The fate which includes whether it was retained or discarded and the reason |  **CODE** from |e.g., |
| Sampling method code | M |  | Two letters code | **CODE** from \_\_\_\_\_ |
| Number of fish | M | The numbers of individuals observed/caught by species and fate (including if recording at an individual animal level) | Integer??? |  |

Weight: The catch weight corresponding to the specified product type recorded in ‘weight code’. If the fish has not been processed, record the unprocessed weight

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Processing type code | O |  | **CODE** from | e.g., |
| Value | O |  | Float |  |
| KG/T | O |  | Indicate units (KG or T) |  |
| Estimation method code | O |  | **CODE** from |  e.g., |
:::

|  |  |  |  |  |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Sampling period code | M |  |**CODE** from  | e.g., |
| Sampling method code | M | The sampling method used for the collection of biological sub-sample | **CODE** from |  e.g., |

# (E-SET-CATCHES-SPECIMEN)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |
| Catch ID | M | refer to parent catch ID | Alphanumeric code |  |
| Specimen ID | M | The specimen number. This should be a four digit numerical code beginning 0001. Specimen numbers should be consecutive within the same catch detail within the same set of the observed trip. | **Code** from  | e.g., |

## Specimen Details

| Element  | Requirement | Description                   | Format | Input value |
|:---------|:-----------:|:------------------------------|:------:|:-----------:|
| Length 1 |      M      | Length of individual specimen |        |             |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type code | M | The length code used for the measurement | **CODE** from | e.g., |
| Value (cm) | M | The length corresponding to the length type taken rounded to the lower centimeter | Float |  |
| Measuring tool code | M | Specify the tool code used for the measurement | **CODE** from | |
| Is straight | M | Yes or No | Yes/No |  |
:::

| Length 2:

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type code | O | The length code used for the measurement | **CODE** from | e.g., |
| Value (cm) | O | The length corresponding to the length type taken rounded to the lower centimeter | Float |  |
| Measuring tool code | O | The tool code used for the measurement | **CODE** from | |
| Is straight | O | Indicate Yes or No | Yes/No |  |
:::

| Weight: The specimen’s weight corresponding to the specified product type recorded in ‘weight code’. If the fish has not been processed, record the unprocessed weight

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Processing type code | O | The processing code used for the weight measurement | **CODE** from | e.g.,|
| Value | O | The weight corresponding to the length type code taken rounded to the...? | Float |  |
| KG/T | O | Indicate units | KG or T |  |
| Estimation method code | O | Method used to estimate weight of specimen | **CODE** from | e.g., |
:::

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Sex | O | The sex of the sampled fish specimen. If unknown record "U" | **Code** from  | e.g., F |

| Maturity: optional reporting
| The stage of maturity of the specimen according to standard maturity scales approved by the IOTC. If unknown record UNK.

::: {style="margin-left:40px"}
| Element | Requirement | Description |            Format            | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Scale   |      O      |             | \*\* MISSING CODES TO DEFINE |             |
| Stage   |      O      |             | \*\* MISSING CODES TO DEFINE |             |
:::

| Sample collected
| The following details on the collection of samples: a) type (e.g. otoliths, spine clippings, and genetic samples) b) preservation method (e.g. alcohol, frozen, etc.) c) destination (i.e. location to be sent/stored)

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type | O |  | \*\*MISSING CODES TO DEFINE |  |
| Preservation method | O |  | \*\*MISSING CODES TO DEFINE |  |
:::

| Depredation method:

::::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| depredation source code | O | For depredated specimens/or catch, record the depredation source based on depredation scar characteristics. For non-depredated specimens record NA | **Code** from  | e.g.,  |
| observed predatory code | O | For depredated specimens/or catch, record the predator species directly observed and identified (FAO spp. 3-alpha code). If the predator was not observed record UNK (unknown). For non-depredated specimens record NA | **Code** from  | e.g., |

# (E-SET-CATCHES-SSI)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |
| Catch ID | M | refer to parent catch ID | Alphanumeric code |  |
| Specimen ID | M | refer to parent specimen ID | 4 digit code |  |

## Additional Catch Details on SSI

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Condition at capture code | M | State the condition of the specimen at capture | **Code** from | e.g.,  |
| Condition at release code | M | State the condition of the specimen at the time of release | **Code** from __| e.g.,   |
| Gear interaction code | M | Specify the type of interaction of the specimen with the fishing gear. In the case of difficulty to collect this information, use the code "UNK" | **Code** from |e.g.,  |
| Hook type code | O | Record the type of hook the individual was hauled on | **Code** from | e.g.,  |
| Bait | O | Record the type and condition of the bait the individual was hauled on | **Code** from | e.g.,  |
| Leader |  |  |  |  |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Material code | M | For SSI only, record the leader material the individual was hauled on (Table 16). [Consistent with IOTC Res 12-04 and IOTC Res. 17/05] - from original ROS description form\*\* | **Code** from  |e.g  |
| Diameter (mm) | O | For SSI only, record the thickness of the leader the individual was hauled on. Note: precise units (preferably millimeters (mm)). [Consistent with IOTC Res 12-04 and IOTC Res. 17/05] - from original ROS description form \*\* | Float |  |
:::

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| De-hooker device code | O | Specify de-hooking or line cutting device used to extract the hook | **Code** from  | e.g.,   |
| Brought onboard | O | Indicate Yes or No, if the specimen was brought onboard | Yes/No |  |
| Handling method code | O | Detail how the specimen was brought onboard | **Code** from | e.g.,  |
| Revival | O | For turtles indicate Yes if the release took place with resuscitation and No if not | Yes/No |  |
| Photo ID | O | If a photo is taken, record photo number/code so that it can be linked back to the specimen for onshore examination | Photo code | e.g., |
| Depredation details |  |  |  |  |

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Depredation source code | O | For depredated specimens/or catch, record the depredation source based on depredation scar characteristics. For non-depredated specimens record NA | **Code** from | e.g.,  |
| Depredation predator code | O | For depredated specimens/or catch, record the predator species directly observed and identified (FAO spp. 3-alpha code). If the predator was not observed record UNK (unknown). For non-depredated specimens record NA | **CODE** from | e.g., |
:::

# (E-SET-TAG-DETAILS)

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Observed trip ID |  | M | refer to parent observed trip |  |
| Set ID | M | refer to parent Set ID | 4 digits number |  |
| Catch ID | M | refer to parent catch ID | Alphanumeric code |  |
| Specimen ID | M | refer to parent specimen ID | 4 digit code |  |

## Tag Details

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Release | O | Indicate Yes or No, whether this individual was re-released with a tag attached. | Yes/No |  |
| Recovery | O | Indicate Yes or No, whether this individual was re-released with a tag attached. | Yes/No |  |
| Type code | O | Record the type of tag used | Two letters code |  |
| Tag number | O | Provide the tag number. If a turtle, provide both tag numbers (right and left flipper). | Alphanumeric code |  |
| Finder name | O |  |  | Free entry. Plain text |
| Finder contact details | O |  |  | Free entry. Plain text |

# Reporting Deadlines

- **Longline fisheries**: 30 June (preliminary), 30 December (final)

# Reference code lists

<!-- ## Entities {#entities} -->

<!-- ```{r collapse = TRUE} -->

<!-- out_dt(ENTITIES, "ENTITIES") -->

<!-- ``` -->
:::::
