---
title: "IOTC statistical data reporting: Form ROS-GN (v`r BASE_VERSION`)"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  word_document2:
    reference_docx: "../templates/doc_template.docx"
    number_sections: FALSE
    reference_num: TRUE
    fig_caption: TRUE
  html_document2:
    css: "../templates/html_template.css"
    includes: 
      in_header: "../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
editor_options: 
  markdown: 
    wrap: 72
---

# Description

This form provides for the reporting of operational and catch data from gillnet fisheries under the IOTC Regional Observer Scheme (ROS). The form is designed to capture verified information on fishing activity, catch composition, and bycatch associated with gillnet operations, including IOTC species, and other bycatch species. The reporting format follows the standards adopted by the IOTC Scientific Committee and includes multiple hierarchical data levels, ranging from trip and set information to species-specific catch and bycatch records. Data collected through this form contribute to scientific assessments of tuna and tuna-like species and support monitoring of the impact of gillnet fisheries on associated and dependent species. CPCs are required to complete the form for gillnet operations covered by the ROS, ensuring consistency, transparency, and quality of the data collected by scientific observers at sea or reviewing data collected with Electronic Monitoring Systems.

REPLACE WITH PROPER FORM LINK Click [here](./Form-ROS-GN.xlsx) to download a blank version of Form-ROS-GN, or [return](./index.html) to the list of all IOTC statistical data reporting forms.

# Data content

Vessel and trip identifiers; effort and gear characteristics (nets, drop lines, sinkers); operational details of each set; catch and bycatch by species in number and weight; fate of catch (retained/discarded); interactions with sharks, seabirds, turtles, and other species; mitigation measures used; size measurements of catch as well as some biological samples.

# Metadata

## Submission information

Fill out focal point information (full name, email, finalization date, and submission date) Fill out organization information (name, email)

## General information

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Reporting year | M |	Gregorian calendar year of the fishing activities reported through the dataset|	4-digit integer| 	e.g., `1996` |
| Reporting entity | M | Three-letter (alpha-3) code of the entity reporting the dataset to the IOTC Secretariat | **Code** from [Entities](#entities) | e.g., `ABW`  |
| Flag / Chartering state | M | 	The country registration of the fishing vessels or chartering flag in case of chartering agreement | **Code** from [Countries](#countries) |e.g., `FRA`  |
| Data source | M | The source of data provided: ‘OAS’ for data collected by Observers at sea and ‘EMS’ for data derived from Electronic Monitoring Systems | String |e.g., `OAS`  |

# (O-INFO) Observer and observed trip information

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| observed_trip_id | M | 	Unique identifier of the fishing trip defined as the concatenation of (i) the observation or trip start date (YYYY-MM-DD), (ii) the IOTC observer identifier, (iii) the IOTC vessel identifier as per Record of Authorised Vessels ([RAV](https://rav.iotc.org/)) and the vessel [gear group](https://data.iotc.org/reference/latest/domain/fisheries/#gearGroups) code as per IOTC classification | Alphanumeric | e.g., `2024-01-23/IOTCFRA001/IOTC012345/GN` |

## Observer Identification

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| observer_iotc_id | M | The unique registration identifier assigned to each observer by the IOTC Secretariat | Alphanumeric | e.g., `IOTC_0976` |
| observer_full_name | M | The full name of the scientific observer who collected the data onboard the fishing vessel, or of the Electronic Monitoring reviewer, recorded as first and last names | String | e.g., `John Doe` |

## Observer trip details

| **Embarkation:** The starting port. If the first observation is available after the departure form the port while the vessel is within port limits, this is still recorded as the observation starting port. If the observation starts at sea outside port limits (onboard observer boarding the vessel via a vessel transfer or EM records not available at the trip starting date due to a recording failure), record "at sea".

::: {style="margin-left:40px"}
| **In port**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The country or EEZ of the observation starting location | **Code** from [Countries](#countries) | e.g.,`FRA` |
| port | O | The port of the observation starting location | **Code** from [Ports](#ports) | e.g., `REUREU` |
:::

::: {style="margin-left:40px"}
| **At sea**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| latitude  | O | The latitude of the observation starting location | Decimal degrees (two decimal places) | e.g., `-20.88` |
| longitude | O | The longitude of the observation starting location | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

::: {style="margin-left:40px"}
||||||
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| date_time_UTC | O | The date and time of the start of observations | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
:::


| **Disembarkation:** The ending port. If the last observation is available after a port launch while the vessel is within port limits, this is still recorded as the observation ending port. If the observation ends at sea outside port limits (onboard observer disembarking the vessel via a vessel transfer or EM records not available at the end of observations due to a recording failure) , record "at sea"

::: {style="margin-left:40px"}
| **In port**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The country or EEZ of the observation ending location | **Code** from [Countries](#countries) | e.g.,`FRA` |
| port | O | The port of the observation ending location | **Code** from [Ports](#ports) | e.g., `REUREU` |
:::

::: {style="margin-left:40px"}
| **At sea**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| latitude | O | The latitude of the observation ending location | Decimal degrees (two decimal places) | e.g., `-20.88` |
| longitude | O | The longitude of the observation ending location | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| date_time_UTC | O | The date and time of the end of observations | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
:::


## Observed trip summary


| **Number of fishing sets:** The total number of gillnet sets deployed by the vessel or observed by the scientific observer during a single fishing trip. Each set corresponds to one complete deployment of the gillnet gear.

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| conducted | M | The total number of fishing sets conducted by the vessel from the observation starting date to the observation ending date, regardless their catch and data collection activities | Integer | **EXAMPLE TO ADD**  |
| observed | M | The total number of fishing sets/events monitored by the observer. In the case of Electronic Monitoring, only processed events to be included | Integer | **EXAMPLE TO ADD** |
:::

| **Number of days:** The total number of hours or calendar days the vessel is on a fishing trip. This can be further categorised by type of activity (e.g., searching, transiting, actively fishing, or present in fishing areas).

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| searching | M | The number of hours/days searching during the observation period | Integer | **EXAMPLE TO ADD** |
| actively fishing | M | The number of active fishing hours/days during the observation period | Integer | **EXAMPLE TO ADD** |
| in_fishing_area | O | The number of hours/days in the fishing area during the observation period | Integer | **EXAMPLE TO ADD** |
| transiting | O | The number of hours/days transiting during the observation period | Integer | **EXAMPLE TO ADD** |
| lost | O | The number of hours/days lost during the observation period | Integer | **EXAMPLE TO ADD** |
:::

| **Reasons for lost days:** Record the reason(s) a vessel was unable to fish: (i) adverse weather conditions, (ii) mechanical breakdown or inoperative gear or (iii) unforeseen events (specify).

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| reason | O | The main reasons for days at sea lost to fishing activity | **Code** from [Reasons for Days Lost](#reasonsDaysLost) | e.g., `AW` |

# (V-INFO) Vessel \> General Information

## Vessel information


| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| observed_trip_id | M | The parent observed trip identifier | Alphanumeric | e.g., `2024-01-23/IOTCFRA001/IOTC012345/GN` |

## Vessel Information

| **Identification:** Unique identifiers and key details of the vessel to uniquely identify the vessel in fisheries and observer records.

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| name | M | The vessel full name as recorded on vessel official documentation or record the vessel full name as imprinted on the vessel itself or Electronic Monitoring records | String | e.g., `HAWWA` |
| flag_or_chartering_state | M | The country code of registration or chartering | **Code** from [Countries](#countries) | e.g., `OMN` |
| iotc_number | M | The unique identification number assigned to the vessel by the IOTC when it is included in the Record of Authorised Vessels | Alphanumeric | e.g., `IOTC003810` |
| imo_number | O | The unique vessel identification number assigned by the International Maritime Organization | Seven-digit number | e.g., `9359698` |
| ircs | O | The unique alphanumeric code (International Radio Call Sign; IRCS) assigned to the vessel for radio communications, as recorded in official registration documents radio call sign (when available) | Alphanumeric | e.g., `A4DP6` |
:::


| **Registration:** Official vessel registration details to uniquely identify the vessel within the national or regional registry.

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The vessel's country of registry | **Code** from [Countries](#countries) | e.g., `FRA` |
| port | O | The vessel's port of registry (also called home port) shown on its registration documents and lettered on the stern of the ship's hull | **Code** from [Ports](#ports) | e.g., `REUREU` |
| registration_number | O | The number issued by country in which the vessel is registered, shown on its registration documents and written on the hull of the vessel | Alphanumeric or numeric entry according to CPC standards | e.g., `CBG303` |
:::

<!-- FORM UPDATES:  Fields for Contact ( phone 1, phone 2, fax 1, fax 2, email 1, email 2 should all be removed) -->

| **Licensed target species**
::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| species 1 | M | The list of species that are intentionally targeted in the fishery | **Code** from [Target Species](#targetSpecies) | e.g., `AL` |
| species 2 | O | The list of species that are intentionally targeted in the fishery | **Code** from [Target Species](#targetSpecies) | e.g., `AL` |
| species 3 | O | The list of species that are intentionally targeted in the fishery | **Code** from [Target Species](#targetSpecies) | e.g., `AL` |
| species 4 | O | The list of species that are intentionally targeted in the fishery | **Code** from [Target Species](#targetSpecies) | e.g., `AL` |
:::

<!--VMS_ON | O | **ADD DESCRIPTION | String | e.g., `Yes` |--> this field is not in form or table from scientific committee

| Main Fishing Gear | M | The vessel main fishing gear | **Code** from [Fishing Gear](#fishingGear) | e.g., `DL` |


| **Vessel Personnel:** Details of the individuals working onboard during the fishing trip as well as the total number of crew members onboard.

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| fishing_master_name | M | The full name of the fishing master recorded as first and last names | String | e.g., `John Doe` |
| fishing_master_nationality | M | The nationality of the fishing master | **Code** from [Countries](#countries) | e.g., `FRA` |
| skipper_captain_name | M | Name of the skipper or captain recorded as first and last names| String | e.g., `John Doe` |
| skipper_captain_nationality | M | Nationality of the skipper or captain | **Code** from [Countries](#countries) | e.g., `FRA` |
| crew_number | O | The number of crew onboard the vessel | Integer | e.g., `26` |
:::

# (V-TRIP) Vessel \> Trip details

| Element | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| observed_trip_id | M | The parent observed trip identifier | Alphanumeric | e.g., `2024-01-23/IOTCFRA001/IOTC012345/GN` |  

## Trip Details

| **Vessel departure:** The name and/or geographical coordinates of the port from where the vessel sailed – also include the country. If the vessel started a new trip at sea following transshipment record 'at-sea’ plus the geographical coordinates corresponding to the location the trip started

::: {style="margin-left:40px"}
| **In port**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The country or EEZ of the observation starting location | **Code** from [Countries](#countries) | e.g., `FRA` |
| port | O | The port of the observation starting location | **Code** from [Ports](#ports) | e.g., `REUREU` |
| latitude | O | The latitude of the observation starting location | Decimal degrees (two decimal places) | e.g., `-20.88` |
| longitude | O | The longitude of the observation starting location | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

::: {style="margin-left:40px"}
|               |     |     |                  |                       |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| date_time_utc |  O  | The date and time (in Coordinated Universal Time, UTC) corresponding to the start of the observation period at the reported location | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
:::

::: {style="margin-left:40px"}
| **At sea**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The country or EEZ of the observation starting location | **Code** from [Countries](#countries) | e.g., `FRA` |
| latitude | O | The latitude of the observation starting location | Decimal degrees (two decimal places) | e.g., `-20.88` |
| longitude | O | The longitude of the observation starting location | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| date_time_UTC | O | The date and time the vessel departed from port or from a transshipment location | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
:::

| **Vessel return:** The name and/or geographical coordinates of the port where the vessel returned – also include the country. If the vessel arrived at a transshipment location record 'at-sea' plus the geographical coordinates corresponding to the location the transshipment started. If the observer disembarked before the vessel returned then record expected port of return as provided by the vessel

::: {style="margin-left:40px"}
| **In port**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The country or EEZ of the observation ending location | **Code** from [Countries](#countries) | e.g., `FRA` |
| port | O | The port of the observation ending location | **Code** from [Ports](#ports) | e.g., `REUREU` |
| latitude | O | The latitude of the observation ending location | Decimal degrees (two decimal places) | e.g., `-20.88` |
| longitude | O | The longitude of the observation ending location | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

::: {style="margin-left:40px"}
|               |     |     |                  |                        |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| date_time_UTC |  O  | The date and time (in Coordinated Universal Time, UTC) corresponding to the end of the observation period at the reported location | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
:::

::: {style="margin-left:40px"}
| **At sea**
:::

::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The country or EEZ of the observation ending location | **Code** from [Countries](#countries) | e.g., `FRA` |
| latitude | O | The latitude of the observation ending location | Decimal degrees (two decimal places) | e.g., `-20.88` |
| longitude | O | The longitude of the observation ending location | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

::: {style="margin-left:40px"}
|  |  |  |  |  |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| date_time_utc | O | The date and time the fishing vessel finishes its fishing campaign, i.e., returns to port or to a transshipment location for unloading. If is the expected date and time of arrival (ETA) if the observer disembarks before the vessel returns | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
:::


# (V-ATTRIBUTES) Vessel \> Vessel attributes

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| observed_trip_id | M | The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |

## Vessel Attributes

| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Tonnage | O | The vessel gross tonnage (no unit) as specified in vessel registration documents | Float | e.g., `2319` |
| Length | O | The vessel overall length (m) as specified in vessel registration documents | Floats | e.g., `84.1` |
| Hull material code | O | The vessel hull material | **Code** from [Hull Material Types](#hullMaterialTypes) | e.g., `AL` |
| gross_tonnage | O | Gross tonnage (GT), a dimensionless measure of vessel's internal volume from registration documents | Integer | e.g., `2319` |
| LOA_m | O | The vessel overall length (m) as specified in vessel registration documents | Floats | e.g., `84.1` |
| Hull material | O | The primary material used in the construction of the vessel's hull | **Code** from [Hull Material Types](#hullMaterialTypes) | e.g., `AL` |

| **Main engines:** The make (brand) and power of the two main engines.

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Make | O | **DESCRIPTION TO ADD** | String | e.g., `MAN Energy Solutions`  |
| Power value | O | **DESCRIPTION TO ADD** | Float | e.g., `5000` |
| Power unit | O | **DESCRIPTION TO ADD** | Power units: kilowatts (kW), horsepower (hp), or break horsepower (hp) | e.g., `kW` |
:::


|  |  |  |  |  |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Fish storage capacity | O | The vessel total maximum capacity to store catches | Float | e.g., `1100` |

| **Fish preservation methods:** The fish preservation methods used by the vessel to preserve the catch, e.g., iced, frozen in brine, deep-frozen
::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Preservation method 1 | O |  |  **Code** from [Fish Preservation Methods](#fishPreservationMethods) | e.g., `BR` |
| Preservation method 2 | O |  |  **Code** from [Fish Preservation Methods](#fishPreservationMethods) | e.g., `BR` |
| Preservation method 3 | O |  |  **Code** from [Fish Preservation Methods](#fishPreservationMethods) | e.g., `BR` |
| Preservation method 4 | O |  |  **Code** from [Fish Preservation Methods](#fishPreservationMethods) | e.g., `BR` |
::: 
| **Fish storage types:** The type of structure(s) present on-board used by the vessel to store the catch
::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Storage type 1 | O |  |  **Code** from [Fish Storage Types](#fishStorageTypes) | e.g., `BF` |
| Storage type 2 | O |  |  **Code** from [Fish Storage Types](#fishStorageTypes) | e.g., `BF` |
| Storage type 3 | O |  |  **Code** from [Fish Storage Types](#fishStorageTypes) | e.g., `BF` |



| **Autonomy range:** Vessel autonomy, expressed by the time (days) a vessel can spend at sea without refuelling. If this information is not available then record vessel range expressed in cruising distance (nm). If a figure for the range cannot be obtained, the observer should calculate vessel range as follows: Vessel range (nm)\> = \<Vessel average cruising distance per metric tonne (nm/t)\> : \<Tonnage of fuel carried (t)\> Note: specify units (days or nautical miles)

::: {style="margin-left:40px"}
| Field | Requirement | Description |      Format       | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Autonomy_range_value | O | The vessel's operational endurance, expressed either as the maximum number of days it can remain at sea without resupply, or as the maximum distance it can cover (in nautical miles, nm) | Float | e.g., `30` |
| Autonomy_range_unit  | O | The unit used to describe the value of autonomy range | days or nm | e.g., `days` |
:::


## Vessel Electronics

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| GNSS | O | Indicates whether or not one or more Global Navigation Satellite System systems (GNSS) such as the US Global Positioning System (GPS) were present on the vessel (Yes/No/Unk) | String | e.g., `Yes` |
| VMS | O | Indicates whether or not one or more Vessel Monitoring Systems (VMS) were present on the vessel (Yes/No/Unk)  | String | e.g., `Yes` |
| AIS | O | Indicates whether or not one or more Automatic Identification Systems (AIS) were present on the vessel (Yes/No/Unk) | String | e.g., `Yes` |
| Radars | O | Indicates whether or not one or more radars were present on the vessel (Yes/No/Unk) | String | e.g., `Yes`  |
| Track plotter | O | Indicates whether or not one or more track plotters were present on the vessel (Yes/No/Unk) | String | e.g., `Yes` |
| Depth sounder | O | Indicates whether or not one or more depth sounders were present on the vessel (Yes/No/Unk)| String | e.g., `Yes` |
| Sonar | O | Indicates whether one or more sonars were present on the vessel (Yes/No/Unk) | String | e.g., `Yes` |
| Doppler current meter | O | Indicates whether one or more doppler current meters were present on the vessel | String | e.g., `Yes` |
| XBT | O | Indicates whether or not one or more expendable bathythermographs (XBT) were present on the vessel | String | e.g., `Yes` |
| VHF radios | O | Indicates whether or not one or more VHF radios weere present on the vessel | String | e.g., `Yes` |
| HF radios | O | Indicates whether one or more HF radios were present or not on the vessel | String | e.g., `Yes` |
| Satellite comms | O | Indicate whether or not one or more satellite communication systems were present on the vessel | String | e.g., `Yes` |
| FIS | O | Indicates whether or not one or more Fisheries Information Services were present on the vessel | String | e.g., `Yes` |


## Waste Management Detail
::: {style="margin-left:40px"}
| Waste Management Detail 1
:::
::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:-----------------|:------------:|:------------------------|:------------:|:------------:|
| Category | O | The category of the waste produced by the vessel |**Code** from [Waste Categories](#wasteCategories) | e.g., `CP` |
| Storage/disposal method | O |	The method used to dispose of the waste | **Code** from [Storage/Disposal Methods](#storageDisposalMethods)| e.g., `AS` |
:::
::: {style="margin-left:40px"}
| Waste Management Detail 2
:::
::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:-----------------|:------------:|:------------------------|:------------:|:------------:|
| Category  | O  |	The category of the waste produced by the vessel | **Code** from [Waste Categories](#wasteCategories) | e.g., `CP` |
| Storage/disposal method | O |	The method used to dispose of the waste | **Code** from [Storage/Disposal Methods](#storageDisposalMethods)| e.g., `AS` |
:::
::: {style="margin-left:40px"}
| Waste Management Detail 3
:::
::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:-----------------|:------------:|:------------------------|:------------:|:------------:|
| Category | O |	The category of the waste produced by the vessel | **Code** from [Waste Categories](#wasteCategories) | e.g., `CP` |
| Storage/disposal method | O |	The method used to dispose of the waste | **Code** from [Storage/Disposal Methods](#storageDisposalMethods)| e.g., `AS` |
:::
::: {style="margin-left:40px"}
| Waste Management Detail 4
:::
::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:-----------------|:------------:|:------------------------|:------------:|:------------:|
| Category   |O  |	The category of the waste produced by the vessel  |**Code** from [Waste Categories](#wasteCategories) | e.g., `CP` |
| Storage/disposal method | O |	The method used to dispose of the waste | **Code** from [Storage/Disposal Methods](#storageDisposalMethods)| e.g., `AS` |
:::


# (G-GENERAL)

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| observed_trip_id | M | The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |

## Gillnet special equipment or machinery

| Field | Requirement | Description | Format | Input value |
|:----------------|:-----------:|:------------|:----------------:|:-----------:|
| Net drum/hauler | M | Indicates if present on board. Vessels are normally equipped with a hydraulic net hauler; However they can also use net drums to both haul and store the net (Yes/NO/Unk)| String | e.g., `Yes` |

## Gillnet attributes (on the reporting form called GILLNET_CONFIGURATIONS) --- is it one entry per gillnet? that is what is insinuated by descriptions...

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Gillnet sequential number | M | Specifies the gillnet sequential number  | Integer  |e.g., **ADD**  |
| Total number of panels | M | The number of panels making up the net | Integer  | e.g., **ADD**  |
| Panels stacked | M | Indicates whether or not any of the panels are stacked (Yes/No/Unk)  | String  | e.g., `Yes`  |
| Net length | M | The net string length. Usually calculated by multiplying the panel average length by the number of panels used in the net |   |  |
| Net depth | O  | The vertical height of the net (depth). Usually obstained by measuring the length of the end-line, or up-and-down the line, on the end of a net where the meshes are attached. This information may be used to cross check information provided by the crew  | Float  | e.g., **ADD**  |
| Net material | O | The material of the net webbing  |**Code** from _____  | e.g., **ADD** |

| **Stretched mesh size(s):** The average stretched lengths (knot to knot) and range of the mesh. Usually calculated by measuring at least 10 meshes from 5 panels in different areas of the net
::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:-----------------|:------------:|:------------------------|:------------:|:------------:|
| value 1 | M |  | Float | e.g., **ADD** |
| unit | M | Indicates units (mm or cm) | String | e.g., `mm`
| value 2 | O |  | Float | e.g., **ADD** |
| unit | O | Indicates units (mm or cm) | String | e.g., `mm`
| value 3 | O |  | Float | e.g., **ADD** |
| unit | O | Indicates units (mm or cm) | String | e.g., `mm`
| value 4 | O |  | Float | e.g., **ADD** |
| unit | O | Indicates units (mm or cm) | String | e.g., `mm`
:::

| Mesh count, vertical | O |The number of vertical meshes of a net in this gear. Usually obtained by counting the number of meshes of the end-line, or up and down line, on the end of a net where the meshes are attached. This information may be used to cross check information provided by the crew  | Integer | e.g., **ADD** |
| Hanging ratio (%) | M | The ratio between the length of the float line and the length of the stretched mesh hanging on the float line. Usually obtained by the following process: 1) counting 10 or 12 meshes horizontally, 2) multiplying the number of counted meshes by average stretched mesh length; 3) measuring the length of the floatline they are attached to, 3) dividing the length of the floatline the meshes are attached to by the length of the stretched meshes counted | Float  |e.g., **ADD**  |

| **Net web colour:** The colour of the net webbing
::: {style="margin-left:80px"}
| Field | Requirement | Description | Format | Input value |
|:-----------------|:------------:|:------------------------|:------------:|:------------:|
| colour 1 | M |  Indicates colour| **Code** from _____ | e.g., **ADD** |
| colour 2 | O |  Indicates colour| **Code** from _____ | e.g., **ADD** |
| colour 3 | O |  Indicates colour| **Code** from _____ | e.g., **ADD** |
| colour 4 | O |  Indicates colour| **Code** from _____ | e.g., **ADD** |
:::

||||||
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Floats type | O | The type of buoyancy aid that is attached to the head-rope | **Code** from ____  | e.g., **ADD**  |
| Float number | O | The approximate total number of floats used on this gillnet. This number must include the number of floats across a space that may occur at the bridle at the end of a net. This information may be obtained from the crew | Integer  | e.g., **ADD**  |
| Distance between floats | O | The average distance (measured along the head-rope) between the floats used on this gillnet | Float | e.g., **ADD** |
| Droplines used | O | Indicates whether or not droplines were used (Yes/No/Unk) | String  | e.g., `Yes`  |
| Droplines length | O | If droplines were used in this gillnet, indicates the length of the droplines. Usually obtained by measuring the distance from the floats (at the water's surface) to the float-line. This information can be used to cross check information provided by the crew  |Float | e.g., **ADD** |
| Sinker type | O | The sinker type attached to the footrope. The type is defined by the material it is made of | **Code** from ____  | e.g., **ADD** |
| Sinker number |O  |Indicates an approximate total number of sinkers attached to the footrope. If more than one type of sinker is used, the indicates approximate total numer of sinker/weghts per sinker type. This information may be obtained from the crew  |Integer |e.g., **ADD**  |
| Sinker average weight | O | The average sinker weight. If more than one type of sinker is used, then is an average weight per sinker type | Float  | e.g., **ADD**  |
- do we need a units column? or is the unit for the sinker always consistent? ^^

# Gillnet Fishing Event

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| Set number | M  | The set number should be a four digit numerical code beginning 0001. Set numbers should be consecutive from the start of the first line to the last line set of the observed trip. A unique number is to be allocated to each individual set | 4-digit number  |e.g., `0004`  |
| Gillnet sequential number | M  | indicates the gillnet used on this set by recording its sequential number | Integer  | e.g., `15` |
**Change Set number to SET ID?**


# (E-SET) Gillnet setting operations

## Setting operations

| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| **Start setting:** The time that the first panel enters the water (ie. start of the setting of the net)

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC at the start of the setting operation | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
| Latitude | O | The latitude of the position at the start of the setting operation | Decimal degrees (two decimal places) | e.g., `-20.88` |
| Longitude | O | The longitude of the position at the start of the setting operation | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

| **End setting:** The time that the gillnet is secured to the vessel, to an anchoring device, or completely deployed (i.e. end of net setting). Gillnet vessels often set dusk and the setting operation may continue beyond midnight into the following day

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC at the end of the setting operation | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
| Latitude | O | The latitude of the position at the end of the setting operation | Decimal degrees (two decimal places) | e.g., `-20.88` |
| Longitude | O | The longitude of the position at the end of the setting operation | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

||||||
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| Vessel speed | O | Record the vessel’s average speed during setting (knots) | Float | e.g., **ADD** |
| Vertical set | M  | Indicates the level the gillnet is set at vertically in the water column, (i.e. if the net is set at the surface or sub-surface)  | **UNSURE OF FORMAT** |  |
| Setting strategy | M  |  | **Code** from ____  |e.g., **ADD**  |
| Setting shape | O |  | **Code** from _____  | e.g., **ADD** |

# Gillnet mitigation measures

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Mititgation measures | M | Indicates whether of not any bycatch mitigation devices were used during the set (Yes/No/Unk) | String | e.g., `Yes`  |
| Mitigation device 1 | O | Indicates any mitigation devices used during the set | **Code** from ____ | e.g., **ADD**  |
| Mitigation device 2 | O | Indicates any mitigation devices used during the set | **Code** from ____ | e.g., **ADD**  |
| Mitigation device 3 | O | Indicates any mitigation devices used during the set | **Code** from ____ | e.g., **ADD**  |
| Mitigation device 4 | O | Indicates any mitigation devices used during the set | **Code** from ____ | e.g., **ADD**  |



# (E-SET-HAULING) Gillnet hauling operations

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| Set number | M  | The set number should be a four digit numerical code beginning 0001. Set numbers should be consecutive from the start of the first line to the last line set of the observed trip. A unique number is to be allocated to each individual set | 4-digit number  |e.g., `0004`  |

## Hauling operations


| **Start hauling:** the time when the hauling equipment is put into gear or when the net starts being hauled. Vessels often haul nets in the early morning after a night soak period

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC  of the start of the hauling operation | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
| Latitude | M | The latitude of the position at the start of the hauling operation | Decimal degrees (two decimal places) | e.g., `-20.88` |
| Longitude | M | The longitude of the position at the start of the hauling operation | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

| **End hauling:** The time when the gillnet is completely retrieved and onboard the vessel

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | O | The date and the time when the gillnet is hauled back on-board | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
| Latitude | O | The latitude of the position at the end of the hauling operation | Decimal degrees (two decimal places) | e.g., `-20.88` |
| Longitude | O | The longitude of the position at the end of the hauling operation | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

||||||
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Net condition | M | Indicated the condition of the net at haul-back, even if the condition was the same as at setting |**Code** from ____  | e.g., **ADD**  |
| Number of net panels retrieved | M | The total number of net panels retrieved at haul | Integer |  |
| Number of net panels observed | M | The total number of hauled net panels that are observed | Integer |  |
| Sampling protocol | M | Indicates the sampling protocol followed by the observer to select which net panels to observe |**Code* from ___ |e.g., **ADD**  |


# (E-SET-CATCHES) Gillnet catch details

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| Set number | M  | The set number should be a four digit numerical code beginning 0001. Set numbers should be consecutive from the start of the first line to the last line set of the observed trip. A unique number is to be allocated to each individual set | 4-digit number  |e.g., `0004`  |
| Gillnet sequential number | M  | indicates the gillnet used on this set by recording its sequential number | Integer  | e.g., `15` |
**Change Set number to SET ID?**

## Catch details

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Species code | M | The species for each specimen observed | **Code** from [All Species](#allSpecies)| e.g., `ABL` |

| **Fate:** The fate which includes whether it was retained or discarded and the reason

::: {style="margin-left:40px"}
| Element              | Requirement | Description | Format  | Input value |
|:---------------------|:-----------:|:------------|:-------:|:-----------:|
| Type | M | **DESCRIPTION TO ADD** | **Code** from [Types of Fate](#fateType) | e.g., `DI` |
| Code | M | **DESCRIPTION TO ADD** | **Code** from [Fates](#fates) | e.g., `DL` |
:::

| Sampling method code | M | **DESCRIPTION TO ADD** |  **Code** from [Sampling Methods for Catch Estimation](#samplingMethodsCatchEstimation) | e.g., `EP` |
| Number of fish | M | The numbers of individuals observed/caught by species and fate (including if recording at an individual animal level) | Integer | **EXAMPLE TO ADD** |

**Weight:** The catch weight corresponding to the specified product type recorded in 'weight code’. If the fish has not been processed, record the unprocessed weight

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Processing type | O | **DESCRIPTION TO ADD** | **Code** from  [Fish Processing Types](#fishProcessingTypes) | e.g., `DR` |
| Value | O | **DESCRIPTION TO ADD** | Float | **EXAMPLE TO ADD** |
| Weight units | O | **DESCRIPTION TO ADD** | Indicate units (kg or tonnes) | e.g., `kg`  |
| Estimation method | O | **DESCRIPTION TO ADD** | **Code** from [Total Catch Estimation](#totalCatchEstimation) | e.g., `EP` |
:::


# (E-SET-CATCHES-SPECIMEN)

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| Set number | M  | The set number should be a four digit numerical code beginning 0001. Set numbers should be consecutive from the start of the first line to the last line set of the observed trip. A unique number is to be allocated to each individual set | 4-digit number  |e.g., `0004`  |
| catch_number | M  |  |   |  |
| specimen_number | M  |  |   |  |
**Change Set number to SET ID?** And same for catch and specimen number?

## Specimen details > Non-target species

| Field | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Condition at capture | M | The condition of the specimen at capture | **Code** from [Individual Conditions](#individualConditions) | e.g., `A0` |
| Condition at release | M | The condition of the specimen at the time of release | **Code** from [Individual Conditions](#individualConditions) | e.g., `A0` |

**It is a bit strange to report non-target species BEFORE target species, no?**

## Specimen details > All species

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Depredation source | O | For depredated specimens/or catch, record the depredation source based on depredation scar characteristics. For non-depredated specimens record NA | **Code** from [Depredation Sources](#depredationSources) | e.g., `BA` |
| Observed predatory | O | For depredated specimens/or catch, the predator species directly observed and identified. If the predator was not observed, the value is 'UNK' (unknown). For non-depredated specimens record, the value is NA (not available) | **Code** from [Predator Species](#predatorSpecies)| e.g., AG15 |


| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Sampling method | M | The sampling method used for the collection of biological sub-sample(s) | **Code** from [Biological Sampling Method](#biologicalSamplingMethod) | e.g., `ES` |

| **Length 1:** Length of individual specimen

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type | M | The type of length used for the measurement | **Code** from [Length Measurements](#lengthMeasurements) | e.g., `CF` |
| Value | M | The value of length corresponding to the length type taken rounded to the lower centimetre | Float | e.g., `34` |
| Measuring tool | M | Specify the tool code used for the measurement | **Code** from [Length Measurement Tools](#lengthMeasurementTools)  |e.g., `CA`  |
| Is straight | M | Indicates whether the size measurement was made straight (Yes/No/Unk) | String | e.g., `Yes` |
:::
<!-- I would remove the "Is straight" field since the type of length measurements indicates how the measurement was taken (straight, curved), and the guidelines for observers should include that the measurements should be taken straight for fish (fork length, total length, etc.) -->

| **Length 2:** **DEFINITION TO ADD?**

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type | O | The length used for the measurement | **Code** from [Length Measurements](#lengthMeasurements)| e.g., `FL` |
| Value | O | The value of length (cm) corresponding to the length type taken rounded to the lower centimetre | Float | e.g., `86` |
| Measuring tool | O | The tool used for the measurement | **Code** from [Length Measurement Tools](#lengthMeasurementTools) | e.g., `CA`  |
| Is straight | O | Indicates whether the size measurement was made straight (Yes/No/Unk) | String | e.g., `No`  |
:::
<!-- I would remove the "Is straight" field since the type of length measurements indicates how the measurement was taken (straight, curved), and the guidelines for observers should include that the measurements should be taken straight for fish (fork length, total length, etc.) -->

| **Weight:** The specimen's weight corresponding to the specified product type recorded in 'weight code'. Unprocessed weight when the fish has not been processed

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Processing type | O | The processing used for the weight measurement | **Code** from [Weight Measurements](#weightMeasurements)  | e.g., `GG` |
| Value | O | The weight corresponding to the measurement type code | Float | e.g., `43.2` |
| KG/T  | O | Unit of weight (kg or t) | String | e.g., `kg` |
| Estimation method code | O | Method used to estimate weight of specimen | **Code** from [Weight Estimation Methods](#weightEstimationMethods) | e.g., `BR` |
:::
<!-- PROPOSAL TO RENAME 'KG/T' to "Weight unit" or "Unit" -->


| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Sex | O | The sex of the sampled fish specimen. If unknown record "U" | **Code** from [Sex](#sex) | e.g., `F` |

| Maturity: optional reporting
| The stage of maturity of the specimen according to standard maturity scales approved by the IOTC. If unknown record UNK.

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Scale | O | **DESCRIPTION TO ADD** | String | **Code list being developed** |
| Stage | O | **DESCRIPTION TO ADD** | String | **Code list being developed** |
:::

| Sample collected: The following details on the collection of samples: a) type (e.g., otoliths, spine clippings, and genetic samples), b) preservation method (e.g., alcohol, frozen, etc.), c) destination (i.e., location to be sent/stored)

::: {style="margin-left:40px"}
| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Type | O | **DESCRIPTION TO ADD** | Code from [Sampling Type](#samplingMethodsForSamplingCollections) | **CODE LIST TO DEVELOP** | **EXAMPLE TO ADD**|
| Preservation method | O | **DESCRIPTION TO ADD** | Code from [Sample Preservation Method](#fishPreservationMethods) | **CODE LIST TO DEVELOP** | **EXAMPLE TO ADD** |
| **Destination** | **DESCRIPTION TO ADD & ADD FIELD TO THE FORMS** | **CODE LIST TO DEVELOP** | **EXAMPLE TO ADD** |
:::


## Tag details 

| Element | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Release | O |  Indicates whether or not the individual was re-released with a tag attached (Yes/No/Unk) | String | e.g., `No` |
| Recovery | O | Indicates whether or not the individual was recovered with a tag attached (Yes/No/Unk) | String  | e.g., `Yes`  |
| Type | O | The type of tag used | **Code** from [Tag Types](#tagTypes) | e.g., `CP` |
| Tag number 1 | O | The tag identifier(s) | Alphanumeric | **EXAMPLE TO ADD** |
| Tag number 2 | O | The tag identifier(s) | Alphanumeric | **EXAMPLE TO ADD** |
| Finder name | O | **DESCRIPTION TO ADD** | String | e.g., `Jane Doe` |
| Finder contact details | O | **DESCRIPTION TO ADD** | String | e.g., `345 Spear Street, San Francisco, CA 94105, USA | (650) 214-6369 | jane.doe@fishing.org` |



# E-SET-CATCHES-SPECIMEN-SSI

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| Set number | M  | The set number should be a four digit numerical code beginning 0001. Set numbers should be consecutive from the start of the first line to the last line set of the observed trip. A unique number is to be allocated to each individual set | 4-digit number  |e.g., `0004`  |
| catch_number | M  |  |   |  |
| specimen_number | M  |  |   |  |
**Change Set number to SET ID?** And same for catch and specimen number?

## Additional catch details on SSIs

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Gear interaction code | O | Specify the type of interaction of the specimen with the fishing gear. In the case of difficulty to collect this information, use the code "UNK" | Two letters code |  |
| Brought onboard | M | Indicate Yes or No, if the specimen was brought onboard | Yes/No |  |
| Handling method code | O | Detail how the specimen was brought onboard | Two letters code |  |
| Revival | O | For turtles indicate Yes if the release took place with resuscitation and No if not | Yes/No |  |
| Photo ID | O | If a photo is taken, record photo number/code so that it can be linked back to the specimen for onshore examination | Photo code |  |


# (T-EVENTS)

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| Observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| Transhipment_number | M  | **ADD DESCRIPTION** |   |e.g., **ADD**  |


## Vessel Transhipment Event


| **Start event:** 

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | M | The date and the time in GMT/UTC  of the start of the transhipment operation | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
| Latitude | M | The latitude of the position at the start of the transhipment operation | Decimal degrees (two decimal places) | e.g., `-20.88` |
| Longitude | M | The longitude of the position at the start of the transhipment operation | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

| **End event:** 

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Date and time | O | The date and the time at the end of the transhipment event | YYYY-MM-DD hh:mm | e.g., `2025-09-15 12:00` |
| Latitude | O | The latitude of the position at the end of the transhipment operation | Decimal degrees (two decimal places) | e.g., `-20.88` |
| Longitude | O | The longitude of the position at the end of the transhipment operation | Decimal degrees (two decimal places) | e.g., `55.53` |
:::

| Field | Requirement | Description | Format | Input value |
|:--------------|:-------------:|:--------------|:-------------:|:-------------:|
| Category code | O |   | **Code** from ___ | e.g., **ADD**


| **Carrier or fishing vessel** 

| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| name | M | The vessel full name as recorded on vessel official documentation or record the vessel full name as imprinted on the vessel itself or Electronic Monitoring records | String | e.g., `HAWWA` |
| flag_or_chartering_state | M | The country code of registration or chartering | **Code** from [Countries](#countries) | e.g., `OMN` |
| ircs | O | The unique alphanumeric code (International Radio Call Sign; IRCS) assigned to the vessel for radio communications, as recorded in official registration documents radio call sign (when available) | Alphanumeric | e.g., `A4DP6` |

| **Registration:** Official vessel registration details to uniquely identify the vessel within the national or regional registry.

::: {style="margin-left:40px"}
| Field | Requirement | Description | Format | Input value |
|:------- |:-----:|:-----------------------|:-------------:|:-------------:|
| country | O | The vessel's country of registry | **Code** from [Countries](#countries) | e.g., `FRA` |
| port | O | The vessel's port of registry (also called home port) shown on its registration documents and lettered on the stern of the ship's hull | **Code** from [Ports](#ports) | e.g., `REUREU` |
| number | O | registration number?? | Alphanumeric or numeric entry according to CPC standards | e.g., `CBG303` |
:::


# (T-PRODUCTS)

| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| observed_trip_number | M |The parent observed trip identifier | Alphanumeric | `2024-01-23/IOTCFRA001/IOTC012345/GN` |
| transhipment_number | M  | **ADD DESCRIPTION** |   |e.g., **ADD**  |


## Product transhipped
| Field | Requirement | Description | Format | Input value |
|:-------------|:------------:|:----------------|:------------:|:------------:|
| species_code | O | description | **Code** from ___ | e.g., **ADD**
| processing_type_code | O | description | **Code** from ___ | e.g., **ADD**

| **Quantity**
| value | O | description | float | e.g., 
| units | O | Indicates units (kg or t) | String | e.g., `kg` | 
































