---
title: "IOTC statistical data reporting forms"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  word_document2:
    reference_docx: "../templates/doc_template.docx"
    number_sections: FALSE
    reference_num: TRUE
    fig_caption: TRUE

  html_document2:
    css: "../templates/html_template.css"
    includes: 
      in_header: "../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
---

# Description

The templates for the submission of fisheries statistics to the IOTC are available as plain Microsoft Excel&trade; spreadsheets to simplify the process of entering and submitting all required information This format allows the reporting officer to enter the data either _directly_ (i.e., by hand) or _programmatically_ (i.e., through automated scripts), for later submission by e-mail or via e-MARIS to the IOTC Secretariat.

# _Default_ forms

## Annual catch data

### Form 1RC{#1RC}

For the submission of estimates of total annual retained catches in live weight stratified by fleet, fishery, main IOTC area, species, and quarter.

#### Resources 

+ [Form description](./Form_1RC.html)
+ [Form template](./Form-1RC.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/1RC/)

### Form 1DI{#1DI}

For the submission of estimates of total annual discard levels (either in live-weight equivalent or in numbers) stratified by fleet, fishery, main IOTC area, species, condition at release, and quarter.

#### Resources 

+ [Form description](./Form_1DI.html)
+ [Form template](./Form-1DI.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/1DI/)

### Form 1DR{#1DR}

For the submission of the matrix of species presence in the catch (retained or discarded) by gear group.

#### Resources 

+ [Form description](./Form_1DR.html)
+ [Form template](./Form-1DR.xlsx)

### Form 1IN{#1IN}

For the submission of interactions of longline and surface fisheries with endangered, threatened, and protected (ETP) species.

#### Resources 

+ [Form description](./Form_1IN.html)
+ [Form template](./Form-1IN.xlsx)

## Active crafts data

### Form 2FC{#2FC}

For the submission of the annual number of operating fishing vessels stratified by fleet, fishery, IOTC main area, boat type, mechanisation type, and size class.

#### Resources 

+ [Form description](./Form_2FC.html)
+ [Form template](./Form-2FC.xlsx)

## Catch and effort data

### Form 3CE{#3CE}

For the submission of species-specific catch and fishing effort stratified by fleet, fishery, regular grid or irregular fishing area, effort unit, species, and month. 

This version of the form allows reporting data for multiple fisheries at the same time.

#### Resources 

+ [Form description](./Form_3CE.html)
+ [Form template](./Form-3CE.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/3CE/)

### Form 3CE-update{#3CE-update}

This version of [Form 3CE](#3CE) is suitable for the reporting of **updated** data for a specific fishery.

#### Resources 

+ [Form description](./Form_3CE-update.html)
+ [Form template](./Form-3CE-update.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/update/1RC/)

### Form 3AA{#3AA}

For the submission of interactions with anchored fish aggregating devices (aFADs) stratified by fleet, fishery, location of the interaction, type of aFAD and activity, and month.

If the interaction is followed by a set, the resulting catches should also be reported stratified by species, fate, and catch unit. 

This version of the form allows reporting data for multiple fisheries at the same time.

#### Resources 

+ [Form description](./Form_3AA.html)
+ [Form template](./Form-3AA.xlsx)

### Form 3AA-update{#3AA-update}

This version of [Form 3AA](#3AA) is suitable for the reporting of **updated** data for a specific fishery.

#### Resources 

+ [Form description](./Form_3AA-update.html)
+ [Form template](./Form-3AA-update.xlsx)

### Form 3DA{#3DA}

For the submission of interactions by purse seine and supply vessels with drifting floating objects (dFOBs, i.e., drifting fish aggregating devices and natural objects) stratified by fleet, vessel, fishery, time and location of the interaction, and type of dFOB.

If the interaction is followed by a set, the resulting catches should also be reported stratified by species, fate, and catch unit. 

This version of the form allows reporting data for multiple vessels at the same time.

#### Resources 

+ [Form description](./Form_3DA.html)
+ [Form template](./Form-3DA.xlsx)

### Form 3DA-update{#3DA-update}

This version of [Form 3DA](#3DA) is suitable for the reporting of **updated** data for a specific vessel.

#### Resources 

+ [Form description](./Form_3DA-update.html)
+ [Form template](./Form-3DA-update.xlsx)

### Form 3BU{#3BU}

For the submission of daily positions of active buoys equipping dFADs and natural floating objects stratified by vessel and time.

#### Resources 

+ [Form description](./Form_3BU.html)
+ [Form template](./Form-3BU.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/3BU/)

## Size-frequency data

### Form 4SF{#4SF}

For the submission of annual length / weight data stratified by fleet, fishery, species, 5°x5° grid, type of measurement, measurement tool, fate, and month. 

This version of the form allows reporting data for multiple fisheries and species at the same time.

#### Resources

+ [Form description](./Form_4SF.html)
+ [Form template](./Form-4SF.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/4SF/)

### Form 4SF-update{#4SF-update}

This version of [Form 4SF](#4SF) is suitable for the reporting of **updated** data for a specific fishery and species

#### Resources 

+ [Form description](./Form_4SF-update.html)
+ [Form template](./Form-4SF-update.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/update/4SF/)

## Socio-economic data

### Form 7PR{#7PR}

[ TBD ]

# _Ad interim_ forms

In order to ensure a smooth transition between the historical data reporting process (which used macro-enabled, self validating Microsoft Excel&trade; spreadsheets) and the [newly proposed IOTC forms](https://iotc.org/documents/WPDCS/19/14), a version of the most common forms has been designed that presents the new form structure while maintaining references to the fishery and target species codes used by the previous IOTC forms.

## Annual catch data

### Form 1RC{#1RC_interim}

A version of [Form 1RC](#1RC) that still uses the _old_ [fishery](https://data.iotc.org/reference/latest/domain/legacy/#fisheries) and target species / [species](https://data.iotc.org/reference/latest/domain/legacy/#species) codes.

#### Resources 

+ [Form description](./interim/Form-1RC_interim.html)
+ [Form template](./interim/Form-1RC_interim.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/interim/1RC/)

### Form 1DI{#1DI_interim}

A version of [Form 1DI](#1DI) that still uses the _old_ [fishery](https://data.iotc.org/reference/latest/domain/legacy/#fisheries) and target species / [species](https://data.iotc.org/reference/latest/domain/legacy/#species) codes 

#### Resources 

+ [Form description](./interim/Form-1DI_interim.html)
+ [Form template](./interim/Form-1DI_interim.xlsx) 
+ [Interactive form validator](https://data.iotc.org/validators/ui/interim/1DI/)

## Active crafts data

### Form 2FC{#2FC_interim}

A version of [Form 2FC](#2FC) that still uses the _old_ [fishery](https://data.iotc.org/reference/latest/domain/legacy/#fisheries) codes.

#### Resources 

+ [Form description](./interim/Form-2FC_interim.html)
+ [Form template](./interim/Form-2FC_interim.xlsx)

## Catch and effort data

### Form 3CE{#3CE_interim}

A version of [Form 3CE](#3CE) that still uses the _old_ [fishery](https://data.iotc.org/reference/latest/domain/legacy/#fisheries) and target species / [species](https://data.iotc.org/reference/latest/domain/legacy/#species) codes.

#### Resources 

+ [Form description](./interim/Form-3CE_interim.html) 
+ [Form template](./interim/Form-3CE_interim.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/interim/3CE/)

### Form 3CE-update{#3CE_interim-update}

This version of [Form 3CE_interim](#3CE_interim) is suitable for the reporting of **updated** data for a specific fishery.

#### Resources 

+ [Form description](./interim/Form-3CE_interim-update.html)
+ [Form template](./interim/Form-3CE_interim-update.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/interim/update/3CE/)

## Size-frequency data

### Form 4SF{#4SF_interim}

A version of [Form 4SF](#4SF) that still uses the _old_ [fishery](https://data.iotc.org/reference/latest/domain/legacy/#fisheries) and target species / [species](https://data.iotc.org/reference/latest/domain/legacy/#species) codes.

#### Resources 

+ [Form description](./interim/Form-4SF_interim.html)
+ [Form template](./interim/Form-4SF_interim.xlsx)
+ [Interactive form validator](https://data.iotc.org/validators/ui/interim/4SF/)

### Form 4SF-update{#4SF_interim-update}

#### Resources 

This version of [Form 4SF_interim](#4SF_interim) is suitable for the reporting of **updated** data for a specific fishery and species.

+ [Form template](./interim/Form-4SF_interim-update.xlsx)
+ [Form description](./interim/Form-4SF_interim-update.html)
+ [Interactive form validator](https://data.iotc.org/validators/ui/interim/update/4SF/)