---
title: "IOTC statistical data reporting: Form 1DR (v`r BASE_VERSION`)"
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  word_document2:
    reference_docx: "../templates/doc_template.docx"
    number_sections: FALSE
    reference_num: TRUE
    fig_caption: TRUE

  html_document2:
    css: "../templates/html_template.css"
    includes: 
      in_header: "../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
---
  
# Description
  
This form supports the reporting of *species presence in the catch (retained and discarded) by gear group* for a given CPC / fleet.

# Resources

Click [here](https://data.iotc.org/reference/latest/forms/Form-1DR.xlsx) to download an empty version of form 1-DR, or [return back](..) to the list of all IOTC statistical data reporting forms.

# Supported resolutions

- Res. [15/01](https://www.iotc.org/cmm/resolution-1501-recording-catch-and-effort-data-fishing-vessels-iotc-area-competence) -- _On the recording of catch and effort data by fishing vessels in the IOTC area of competence_
- Res. [18/07](https://www.iotc.org/cmm/resolution-1807-measures-applicable-case-non-fulfilment-reporting-obligations-iotc) -- _On measures applicable in case of non-fulfilment of reporting obligations in the IOTC_

# Reference species groups

-   **IOTC species** [ mandatory ]
-   **Sharks** [ mandatory ]
-   **Mobulids and rays** [ mandatory ]


# Reporting deadlines

-   **All fisheries**: 30 June (final)

# Stratification

## Main data fields (already embedded in the form)

-   [Fishery](#fisheries)
-   [Species](#allSpecies)

## Additional Data fields

-  Matrix table with species in rows and gear groups in columns. For each species/gear combination, the cell must be filled with either a value of 'one' (1) in case of positive catch or a value of 'zero' (0) in case of absence of catch (i.e., no landing and no discard). For shaded cells, the species/gear combination is not expected. 

# Referenced codelists

### Countries (ADM.COU) {#countries}

Reference codes modeling the flag / reporting country submitting a dataset to the IOTC Secretariat.

```{r collapse = TRUE}
out_dt(COUNTRIES, "COUNTRIES")
```


