---
title: "IOTC Data Reporting Forms (v`r DOI_VERSION`)"
subtitle: "`r paste0('Last updated: ', format(Sys.time(), format = '%d %B %Y'))`"   #%F %r %Z
author: "Author: [IOTC Secretariat](mailto:IOTC-Secretariat@fao.org)" 
output:
  word_document2:
    reference_docx: "../templates/doc_template.docx"
    number_sections: FALSE
    reference_num: TRUE
    fig_caption: TRUE

  html_document2:
    css: "../templates/fao_template_simplified.css"
    includes: 
      in_header: "../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
---

# Overview

Following Article XI of the [Agreement for the establishment of the Indian Ocean Tuna Commission](https://iotc.org/sites/default/files/documents/2012/5/25/IOTC%20Agreement.pdf) (IOTC), [Contracting Parties and Cooperating Non-Contracting Parties](https://iotc.org/about-iotc/structure-commission) (CPCs) are required to collect and report fisheries data in accordance with the [Conservation and Management Measures](https://iotc.org/cmms) (CMMs). To manage the data received from CPCs and other parties fishing in the IOTC area of competence for IOTC-managed species, the Secretariat has developed specific reporting forms for each dataset. The forms include all mandatory metadata, data fields, and information on IOTC formats and standard code lists.

All IOTC code lists required by the forms are distributed through the [IOTC Reference Data Catalogue](../) and are also made available via an R library hosted on the IOTC Secretariat's GitHub repository ([iotc-data-reference-codelists](https://github.com/iotc-secretariat/iotc-data-reference-codelists)), with a mirror maintained by the Fisheries Data Interoperability Working Group ([fdiwg](https://github.com/fdiwg/fdi-codelists/tree/main/regional/iotc)). In addition, the code lists have been published on the Zenodo platform to support versioning, citation, and long-term accessibility ([https://doi.org/10.5281/zenodo.15743874](https://zenodo.org/records/15743875)).

# Statistical Fishery Datasets

At its 26^th^ session, the IOTC Scientific Committee endorsed the adoption of new reporting forms to streamline data flow and improve the quality of dataset submissions to the Secretariat. The use of the forms for submitting the core fisheries statistics to the IOTC became **mandatory** as of 2025 (section [Mandatory Forms](#mandatory)). In addition, the Secretariat has developed some voluntary forms for reporting fishing craft statistics, price time series, information on lost gears, and morphometric and biological data (section [Voluntary Forms](#voluntary)).

The forms are available as plain Microsoft Excel™ spreadsheets, allowing reporting officers to input data either manually or programmatically using automated scripts. You can download all current form templates for submitting data to the IOTC [here](../forms/IOTC-stats-forms.zip). They are also available on the Zenodo platform, which is used to manage their different versions and to maintain links with the corresponding IOTC code list versions [https://doi.org/10.5281/zenodo.16941787](https://zenodo.org/records/16941788).

We welcome your feedback on these forms and encourage you to direct any questions to the IOTC Secretariat via email at [IOTC-Statistics@fao.org](mailto:IOTC-Statistics@fao.org).

## Mandatory Forms {#mandatory}

### Form 1DR {#1DR}

For the submission of data on [_species presence in the catch_](https://data.iotc.org/reference/latest/guidelines/#Species_presence_in_the_catch).

+ [Form template](./Form-1DR.xlsx)
+ [Form description](./Form-1DR.html)
<!-- + [Form example]() -->

### Form 1IN {#1IN}

For the submission of data on [_interactions of longline and surface fisheries with endangered, threatened, and protected (ETP) species_](https://data.iotc.org/reference/latest/guidelines/#Interactions_with_Endangered,_Threatened_and_Protected_species).

+ [Form template](./Form-1IN.xlsx)
+ [Form description](./Form-1IN.html)

### Form 1RC {#1RC}

For the submission of data on the total [_amount of fish caught and retained_](https://data.iotc.org/reference/latest/guidelines/#Amount_of_fish_caught_and_retained).

+ [Form template](./Form-1RC.xlsx)
+ [Form description](./Form-1RC.html)
+ [Form validator](https://data.iotc.org/validators/ui/1RC/)

### Form 1DI {#1DI}

For the submission of data on the [_amount of discards_](https://data.iotc.org/reference/latest/guidelines/#Amount_of_discards).

+ [Form template](./Form-1DI.xlsx)
+ [Form description](./Form-1DI.html)
+ [Form validator](https://data.iotc.org/validators/ui/1DI/)

### Form 3CE {#3CE}

For the submission of data on [_geo-referenced catches and efforts_](https://data.iotc.org/reference/latest/guidelines/#Geo-referenced_catches_and_efforts).

The unified form allows reporting data for multiple fisheries simultaneously:

+ [Form template](./Form-3CE.xlsx)
+ [Form description](./Form-3CE.html)
+ [Form validator](https://data.iotc.org/validators/ui/3CE/)

A version of the form allows reporting **updated** data for a single fishery:

+ [Form template](./Form-3CE-update.xlsx)
+ [Form description]( ./Form-3CE-update.html)
+ [Form validator](https://data.iotc.org/validators/ui/update/3CE/)

### Form 3AA {#3AA}

For the submission of data on [_activities related to anchored fish aggregating devices_](https://data.iotc.org/reference/latest/guidelines/#AFAD-related_activities).

The unified form allows reporting data for multiple fisheries simultaneously:

+ [Form template](./Form-3AA.xlsx)
+ [Form description](./Form-3AA.html)

A version of the form allows reporting **updated** data for a single fishery:

+ [Form template](./Form-3AA-update.xlsx)
+ [Form description](./Form-3AA_update.html)

### Form 3BU {#3BU}

For the submission of data on [_daily buoy positions_](https://data.iotc.org/reference/latest/guidelines/#Daily_buoy_positions).

+ [Form template](./Form-3BU.xlsx)
+ [Form description](./Form-3BU.html)
+ [Form validator](https://data.iotc.org/validators/ui/3BU/)

### Form 3DA {#3DA}

For the submission of data on [_interactions related to drifting floating objects_](https://data.iotc.org/reference/latest/guidelines/#DFOB-related_activities).

The unified form addresses the shortcomings of the previous 3FA form and allows reporting data for multiple vessels simultaneously:

+ [Form template](./Form-3DA.xlsx)
+ [Form description](./Form-3DA.html)

A version of the form allows reporting **updated** data for a single vessel:

+ [Form template](./Form-3DA-update.xlsx)
+ [Form description](./Form-3DA-update.html)

### Form 4SF {#4SF}

For the submission of data on [_geo-referenced size frequencies_](https://data.iotc.org/reference/latest/guidelines/#Geo-referenced_size_frequencies).

The unified form allows reporting data for multiple fisheries and species simultaneously:

+ [Form template](./Form-4SF.xlsx)
+ [Form description](./Form-4SF.html)
+ [Form validator](https://data.iotc.org/validators/ui/4SF/)

A version of the form allows reporting **updated** data for a single fishery and species:

+ [Form template](./Form-4SF-update.xlsx)
+ [Form description](./Form-4SF-update.html)
+ [Form validator](https://data.iotc.org/validators/ui/update/4SF/)

## Voluntary Forms {#voluntary}

### Form 2FC {#2FC}

For the submission of data on [_fishing craft statistics_](https://data.iotc.org/reference/latest/guidelines/#Fishing_craft_statistics).

+ [Form template](./Form-2FC.xlsx)
+ [Form description](./Form-2FC.html)

### Form 5MB {#5MB}

For the submission of individual-level morphometric (lengths and weights) and biological data, including sex, maturity stage, and samples of hard and soft tissues for further analysis.

+ [Form template](./Form-5MB.xlsx)
+ [Form description](./Form-5MB.html)

### Form 6LG

For the submission of data and information on the recovery of abandoned, lost or discarded fishing gear in accordance with IOTC Recommendation [24/11](https://iotc.org/cmm/recommendation-2411-conservation-and-management-measure-marine-pollution) on _Conservation and Management Measure on Marine Pollution_.

+ [Form template](./Form-6LG.xlsx)
+ [Form description](./Form-6LG.html)

### Form 7PR {#7PR}

For the submission of data on _prices of fish products for tuna and tuna-like species under IOTC mandate_. Specifications for a new IOTC Form for fish prices and other socio-economic indicators are expected to be defined through the work conducted by the [Working Party on Socio-Economics](https://iotc.org/meetings/1st-working-party-socio-economics).

+ [Legacy form template](./legacy/Form-7PR-legacy.xlsm)
+ [Legacy form description](./legacy/Form-7PR-legacy.html)

# Regional Observer Scheme Datasets

The IOTC Regional Observer Scheme (ROS) was established to collect verified catch and scientific data on tuna and tuna-like species within the IOTC area. Its implementation, which began on 1 July 2010, is carried out entirely at the national level by IOTC Contracting Parties and Cooperating Non-Contracting Parties (CPCs). Information on the ROS, including programme standards and observer training materials, is available on the [ROS page](https://iotc.org/science/regional-observer-scheme-science) of the IOTC website.

The ROS data reporting forms were revised during the 20^th^ Session of the Working Party on Data Collection and Statistics ([WPDCS20](https://iotc.org/meetings/20th-working-party-data-collection-and-statistics-wpdcs20)), held in November 2024, and were subsequently endorsed by the Scientific Committee at its 27^th^ Session ([SC27](https://iotc.org/meetings/27th-session-scientific-committee-sc27)). The forms are provided as XLSX spreadsheets and contain multiple sheets corresponding to different hierarchical levels of data to be reported. They are available in four distinct gear group versions—gillnets, longlines, pole-and-line, and purse seines — corresponding to the main gears used in fisheries subject to the ROS data requirements, i.e., those involving vessels larger than 24 metres in length overall, or vessels smaller than 24 metres operating in Areas Beyond National Jurisdiction (ABNJ).

## Form ROS-GN | Gillnets

+ [Form template](./ros/Form-ROS-GN.xlsx)
+ [Form description](./ros/Form-ROS-GN.html)

## Form ROS-LL | Longlines

+ [Form template](./ros/Form-ROS-LL.xlsx)
+ [Form description](./ros/Form-ROS-LL.html)

## Form ROS-PL | Pole-and-Lines

+ [Form template](./ros/Form-ROS-PL.xlsx)
+ [Form description](./ros/Form-ROS-PL.html)

## Form ROS-PS | Purse Seines

+ [Form template](./ros/Form-ROS-PS.xlsx)
+ [Form description](./ros/Form-ROS-PS.html)

# Vessel Registry Datasets {#5VE}

Information and data on vessels involved in tuna and tuna-like fisheries in the IOTC Area of Competence must be collected and reported in line with the requirements set out in Resolutions [10/08](https://www.iotc.org/cmm/resolution-1008-concerning-record-active-vessels-fishing-tunas-and-swordfish-iotc-area) and [19/04](https://www.iotc.org/cmm/resolution-1904-concerning-iotc-record-vessels-authorised-operate-iotc-area-competence).

## Record of Authorised Vessels {#RAV}

For the submission of data on vessels from longline and surface fisheries authorised to operate in the IOTC Area of Competence, including information on vessel identification, ownership, operator details, fishing gear, and vessel characteristics (e.g. type, length, and gross tonnage).

+ [Form template](https://iotc.org/sites/default/files/documents/compliance/erav/Res_19_04_-_Record_of_IOTC_AFVs_E-FULL_VESSEL.xlsx)
+ [Form description](https://iotc.org/e-rav)

## Active Vessel List {#AVL}

For the submission of data on vessels from longline and surface fisheries that operated in the IOTC Area of Competence in the year prior to reporting, including information on vessel identification, ownership, operator details, fishing gear, and vessel characteristics (e.g. type, length, and gross tonnage).

+ [Form template](https://iotc.org/sites/default/files/documents/compliance/report_templates/Res_10_08_-_Reporting_template_for_active_domestic_vessels_E_F.xlsx)
+ [Form description](https://iotc.org/compliance/reporting-templates)


