---
title: "Formulaires de déclaration des statistiques de pêches à la CTOI"
author: "Author: [Secrétariat de la CTOI](mailto:IOTC-Secretariat@fao.org)" 
output:
  html_document2:
    css: "../templates/fao_template_simplified.css"
    mathjax: null
    includes: 
      in_header: "../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
---

# Présentation

Conformément à l'Article XI de l'Accord portant création de la Commission des Thons de l'océan Indien (CTOI), les Parties contractantes et les Parties non contractantes coopérantes ([CPC](https://iotc.org/sites/default/files/documents/2012/5/25/Accord%20CTOI.pdf)) sont tenues de collecter et de communiquer les données relatives à la pêche conformément aux Mesures de Conservation et de Gestion ([CMG](https://iotc.org/fr/mcgs)). Pour gérer les données reçues des CPC et des autres parties pêchant dans la zone de compétence de la CTOI les espèces sous mandat la CTOI, le Secrétariat a développé des formulaires de déclarations de données spécifiques à chaque jeu de données. L'utilisation de ces formulaires pour soumettre les statistiques de pêche à la CTOI est fortement recommandée, car ils incluent toutes les métadonnées et données obligatoires ainsi que les informations portant sur les formats et les listes de codes standard de la CTOI.

# Jeux de Données Statistiques sur la Pêche

Lors de sa 26^ième^ session, le Comité Scientifique de la CTOI a approuvé l'adoption de nouveaux formulaires de déclaration afin de rationaliser le flux de données et d'améliorer la qualité des jeux de données soumis au secrétariat. L'utilisation de ces formulaires pour la déclaration des statistiques de pêche à la CTOI est devenue **obligatoire** à partir de 2025.

Les formulaires sont disponibles sous forme de feuilles de calcul Microsoft Excel™ simples, permettant aux agents déclarants de saisir les données soit manuellement, soit de manière programmée à l'aide de scripts automatisés.

Vous pouvez télécharger tous les modèles de formulaires pour déclarer les données pour l'année statistique 2024 [ici](../forms/IOTC-forms.zip). Nous vous invitons à nous faire part de vos commentaires sur ces formulaires et vous encourageons à adresser vos questions au Secrétariat de la CTOI par courriel à [IOTC-Statistics@fao.org](mailto:IOTC-Statistics@fao.org).

## Formulaire 1DR {#1DR}

Pour la déclaration de données sur la [_présence d’espèces dans les captures_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Pr%C3%A9sence_d%E2%80%99esp%C3%A8ces_dans_les_captures).

+ [Modèle de formulaire](./Form-1DR.xlsx)
+ [Description du formulaire](./Form-1DR.html)

## Formulaire 1IN {#1IN}

Pour la déclaration de données sur les [_interactions avec les espèces en voie de disparition, menacées et protégées (ETP)_](https://data.iotc.org/reference/latest/guidelines/#Interactions_with_Endangered,_Threatened_and_Protected_species).

+ [Modèle de formulaire](./Form-1IN.xlsx)
+ [Description du formulaire](./Form-1IN.html)

## Formulaire 1RC {#1RC}

Pour la déclaration des données sur les [_quantités de poissons capturés et conservés à bord_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Interactions_avec_les_esp%C3%A8ces_en_voie_de_disparition,_menac%C3%A9es_et_prot%C3%A9g%C3%A9es).

+ [Modèle de formulaire](./Form-1RC.xlsx)
+ [Description du formulaire](./Form-1RC.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/1RC/)

## Formulaire 1DI {#1DI}

Pour la déclaration de données sur les [_quantités de poissons rejetés en mer_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Quantit%C3%A9s_de_poissons_rejet%C3%A9s_en_mer).

+ [Modèle de formulaire](./Form-1DI.xlsx)
+ [Description du formulaire](./Form-1DI.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/1DI/)

## Formulaire 3CE {#3CE}

Pour la déclaration de données sur les [_captures et efforts de pêche géo-référencés_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Captures_et_efforts_de_p%C3%AAche_g%C3%A9o-r%C3%A9f%C3%A9renc%C3%A9s).

Le formulaire unifié permet de déclarer simultanément des données pour plusieurs pêcheries à la fois :

+ [Modèle de formulaire](./Form-3CE.xlsx)
+ [Description du formulaire](./Form-3CE.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/3CE/)

Une version du formulaire permet de déclarer des données **mises à jour** pour une seule pêcherie :

+ [Modèle de formulaire](./Form-3CE-update.xlsx)
+ [Description du formulaire]( ./Form-3CE-update.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/update/3CE/)

## Formulaire 4SF {#4SF}

Pour la déclaration de données sur les [_fréquences de taille géo-référencées_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Fr%C3%A9quences_de_taille_g%C3%A9o-r%C3%A9f%C3%A9renc%C3%A9es).

Le formulaire unifié permet de déclarer des données pour plusieurs pêches et espèces simultanément :

+ [Modèle de formulaire](./Form-4SF.xlsx)
+ [Description du formulaire](./Form-4SF.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/4SF/)

Une version du formulaire permet de déclarer des données **mises à jour** pour une seule pêcherie et une seule espèce :

+ [Modèle de formulaire](./Form-4SF-update.xlsx)
+ [Description du formulaire](./Form-4SF-update.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/update/4SF/)

## Formulaire 3AA {#3AA}

Pour la déclaration de données sur les [_activités liées aux DCP ancrés_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Activit%C3%A9s_li%C3%A9es_aux_DCP_ancr%C3%A9s).

Le formulaire unifié permet de déclarer simultanément des données pour plusieurs pêcheries :

+ [Modèle de formulaire](./Form-3AA.xlsx)
+ [Description du formulaire](./Form-3AA.html)

Une version du formulaire permet de déclarer des données **mises à jour** pour une seule pêcherie :

+ [Modèle de formulaire](./Form-3AA-update.xlsx)
+ [Description du formulaire](./Form-3AA_update.html)

## Formulaire 3DA{#3DA}

Pour la déclaration de données sur les [_activités liées aux objects flottants dérivants_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Activit%C3%A9s_li%C3%A9es_aux_objects_flottants_d%C3%A9rivants).

Le formulaire unifié comble les lacunes de l'ancien formulaire 3FA et permet de déclarer des données pour plusieurs navires simultanément :

+ [Modèle de formulaire](./Form-3DA.xlsx)
+ [Description du formulaire](./Form-3DA.html)

Une version du formulaire permet de déclarer des données **mises à jour** pour un seul navire :

+ [Modèle de formulaire](./Form-3DA-update.xlsx)
+ [Description du formulaire](./Form-3DA-update.html)

## Formulaire 3BU {#3BU}

Pour la déclaration de données sur les [_positions journalières des balises_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Positions_journali%C3%A8res_des_balises).

+ [Modèle de formulaire](./Form-3BU.xlsx)
+ [Description du formulaire](./Form-3BU.html)
+ [Validateur du formulaire](https://data.iotc.org/validators/ui/3BU/)

## Formulaire 2FC {#2FC}

Pour la déclaration de données sur les [_statistiques des bateaux de pêche_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Statistiques_des_bateaux_de_p%C3%AAche).

+ [Modèle de formulaire](./Form-2FC.xlsx)
+ [Description du formulaire](./Form-2FC.html)

## Formulaire 7PR {#7PR}

Pour la déclaration de données sur les _prix des produits de la pêche pour le thon et les espèces apparentées dans le cadre du mandat de la CTOI_. Les spécifications d'un nouveau formulaire CTOI pour les prix du poisson et d'autres indicateurs socio-économiques seront définies dans le cadre des travaux menés par le [Groupe de Travail sur la Socio-Economie] (https://www.iotc.org/meetings/1st-working-party-socio-economics).

+ [Modèle historique de formulaire](./legacy/Form-7PR-legacy.xlsm)

# Jeux de Données du Mécanisme Régional D'Observateurs Scientifiques

Le mécanisme Régional d'Observateurs (MRO) de la CTOI a été établi pour collecter des données de capture et des données scientifiques vérifiées sur les thonidés et les espèces apparentées dans la zone de la CTOI. Sa mise en oeuvre, qui a débuté le 1er juillet 2010, est entièrement réalisée au niveau national par les Parties Contractantes de la CTOI et les Parties Coopérantes non-Contractantes (CPC). Des informations sur le MRO, y compris les normes du programme et le matériel de formation des observateurs, sont disponibles sur la [page web](https://iotc.org/science/regional-observer-scheme-science) du MRO sur le site web de la CTOI.

Les formulaires de déclaration de données du MRO ont été révisés lors de la 20^ième^ session du Groupe de Travail sur la Collecte des Données et les Statistiques ([GTDCS20](https://iotc.org/meetings/20th-working-party-data-collection-and-statistics-wpdcs20)), tenue en novembre 2024, et ont ensuite été approuvés par le Comité Scientifique lors de sa 27^ième^ session ([CS27](https://iotc.org/fr/reunions/27e-comit%C3%A9-scientifique)). Les formulaires sont fournis sous forme de feuilles de calcul XLSX et contiennent plusieurs feuilles correspondant à différents niveaux hiérarchiques de données à déclarer. Ils sont disponibles en quatre versions distinctes de groupes d'engins - filets, palangres, cannes, et sennes - correspondant aux principaux engins utilisés dans les pêcheries soumises aux exigences des données du MRO, c'est-à-dire celles impliquant des navires de plus de 24 mètres de longueur hors tout, ou des navires de moins de 24 mètres opérant dans des zones situées au-delà de la juridiction nationale (ZAJN).

## Formulaire ROS-GN | Filets

+ [Modèle de formulaire](https://iotc.org/sites/default/files/documents/science/ROS-files/reporting/1.0.0/ROS_GN_data_reporting.xlsx)

## Formulaire ROS-LL | Palangres

+ [Modèle de formulaire](https://iotc.org/sites/default/files/documents/data/ROS_Forms_2025/IOTC_ROS_LL_reporting_form.xlsx)

## Formulaire ROS-PL | Cannes

+ [Modèle de formulaire](https://iotc.org/sites/default/files/documents/data/ROS_Forms_2025/IOTC_ROS_PL_reporting_form.xlsx)

## Formulaire ROS-PS | Sennes

+ [Modèle de formulaire](https://iotc.org/sites/default/files/documents/data/ROS_Forms_2025/IOTC_ROS_PS_reporting_form.xlsx)
