---
title: "Formulaires de déclaration des statistiques de pêches à la CTOI"
author: "Author: [Secrétariat de la CTOI](mailto:IOTC-Secretariat@fao.org)" 
output:
  word_document2:
    reference_docx: "../templates/doc_template.docx"
    number_sections: FALSE
    reference_num: TRUE
    fig_caption: TRUE

  html_document2:
    css: "../templates/html_template.css"
    includes: 
      in_header: "../templates/google-analytics.html"
    number_sections: FALSE
    toc: yes
    toc_float:
      collapsed: FALSE
    smooth_scroll: FALSE
---

# Présentation

Conformément à l'Article XI de l'Accord portant création de la Commission des Thons de l'océan Indien (CTOI), les Parties contractantes et les Parties non contractantes coopérantes ([CPC](https://iotc.org/sites/default/files/documents/2012/5/25/Accord%20CTOI.pdf)) sont tenues de collecter et de communiquer les données relatives à la pêche conformément aux Mesures de Conservation et de Gestion ([CMG](https://iotc.org/fr/mcgs)). Pour gérer les données reçues des CPC et des autres parties pêchant dans la zone de compétence de la CTOI les espèces sous mandat la CTOI, le Secrétariat a développé des formulaires de déclarations de données spécifiques à chaque jeu de données. L'utilisation de ces formulaires pour soumettre les statistiques de pêche à la CTOI est fortement recommandée, car ils incluent toutes les métadonnées et données obligatoires ainsi que les informations portant sur les formats et les listes de codes standard de la CTOI.

#### Formulaires historiques de déclaration de données 

Les formulaires actuels de déclaration de données, appelés "historiques", sont disponibles sous forme de feuilles de calcul Microsoft Excel™ compatibles avec les macros. Ces formulaires intègrent des contrôles de saisie et des listes de codes nécessaires pour certaines données spécifiques. Des conseils pour remplir ces formulaires sont fournis dans la version historique des Directives de Déclaration des Données de la CTOI, accessible [ici](./legacy/IOTC_Data_Reporting_Guidelines_2014.pdf).

Vous pouvez télécharger tous les modèles historiques de formulaires [ici](../forms/legacy/IOTC-forms-current.zip). Cette archive ZIP comprend les formulaires historiques utilisés pour les jeux de données principaux de la CTOI sur la pêche, ainsi que les formulaires [1IN](#1IN), [3AA](#3AA), et [3DA](#3DA). Ces formulaires sont adaptés pour répondre aux exigences spécifiques en matière de données relatives aux interactions avec les espèces en danger, menacées et protégées (1IN), aux activités liées à l'AFAD (3AA), et aux activités liées à la DPBF (3DA).

#### Nouveaux formulaire de déclaration de données

Les nouveaux formulaires de déclaration de données sont disponibles sous forme de feuilles de calcul Microsoft Excel™ simples afin de rationaliser la saisie et la déclaration de toutes les informations requises. Ce format permet aux agents déclarants de saisir les données soit manuellement, soit de manière programmée à l'aide de scripts automatisés. Les CPC sont encouragées à se familiariser avec ces nouveaux formulaires et à les tester pour la déclaration des données de l'année statistique 2023.

Vous pouvez télécharger tous les nouveaux modèles de formulaires (uniquement disponibles en anglais pour le moment) pour soumettre les données de l'année statistique 2023 [ici](../forms/IOTC-forms-new.zip). Nous vous invitons à nous faire part de vos commentaires sur ces nouveaux formulaires et nous vous encourageons à adresser vos questions au Secrétariat de la CTOI par courrier électronique à l'adresse suivante : IOTC-Statistics@fao.org.

## Formulaire 1DR {#1DR}

Pour la déclaration de données sur la [_présence d’espèces dans les captures_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Pr%C3%A9sence_d%E2%80%99esp%C3%A8ces_dans_les_captures).

+ [Modèle historique de formulaire](./legacy/Form-1DR-legacy.xlsx)
+ [Nouveau modèle de formulaire](./Form-1DR.xlsx)
+ [Description du nouveau formulaire](./Form_1DR.html)

## Formulaire 1IN {#1IN}

Pour la déclaration de données sur les [_interactions avec les espèces en voie de disparition, menacées et protégées (ETP)_](https://data.iotc.org/reference/latest/guidelines/#Interactions_with_Endangered,_Threatened_and_Protected_species).

+ [Modèle de formulaire](./Form-1IN.xlsx)
+ [Description du formulaire](./Form_1IN.html)

## Formulaire 1RC {#1RC}

Pour la déclaration des données sur les [_quantités de poissons capturés et conservés à bord_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Interactions_avec_les_esp%C3%A8ces_en_voie_de_disparition,_menac%C3%A9es_et_prot%C3%A9g%C3%A9es).

+ [Modèle historique de formulaire](./legacy/Form-1RC-legacy.xlsm)
+ [Nouveau modèle de formulaire](./Form-1RC.xlsx)
+ [Description du nouveau formulaire](./Form_1RC.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/1RC/)

## Formulaire 1DI {#1DI}

Pour la déclaration de données sur les [_quantités de poissons rejetés en mer_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Quantit%C3%A9s_de_poissons_rejet%C3%A9s_en_mer).

+ [Modèle historique de formulaire](./legacy/Form-1DI-legacy.xlsm)
+ [Nouveau modèle de formulaire](./Form-1DI.xlsx)
+ [Description du nouveau formulaire](./Form_1DI.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/1DI/)

## Formulaire 3CE {#3CE}

Pour la déclaration de données sur les [_captures et efforts de pêche géo-référencés_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Captures_et_efforts_de_p%C3%AAche_g%C3%A9o-r%C3%A9f%C3%A9renc%C3%A9s).

Les anciens formulaires sont séparés pour :

+ Les pêcheries côtières: [Modèle historique de formulaire](./legacy/Form-3AR-legacy.xlsm)
+ Les pêcheries palangrières et de surface: [Modèle historique de formulaire](./legacy/Form-3CE-legacy.xlsm)
+ Les navires auxiliaires : [Modèle historique de formulaire](./legacy/Form-3SU-legacy.xlsm)

Le nouveau formulaire unifié permet de déclarer simultanément des données pour plusieurs pêcheries à la fois :

+ [Nouveau modèle de formulaire](./Form-3CE.xlsx)
+ [Description du nouveau formulaire](./Form_3CE.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/3CE/)

Une version du formulaire permet de déclarer des données **mises à jour** pour une seule pêcherie :

+ [Nouveau modèle de formulaire](./Form-3CE-update.xlsx)
+ [Description du nouveau formulaire]( ./Form_3CE_update.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/update/3CE/)

## Formulaire 4SF {#4SF}

Pour la déclaration de données sur les [_fréquences de taille géo-référencées_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Fr%C3%A9quences_de_taille_g%C3%A9o-r%C3%A9f%C3%A9renc%C3%A9es).

Le nouveau formulaire unifié permet de déclarer des données pour plusieurs pêches et espèces simultanément :

+ [Legacy Modèle de formulaire](./legacy/Form-4SF-legacy.xlsm)
+ [Nouveau modèle de formulaire](./Form-4SF.xlsx)
+ [Description du nouveau formulaire](./Form_4SF.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/4SF/)

Une version du formulaire permet de déclarer des données **mises à jour** pour une seule pêcherie et une seule espèce :

+ [Nouveau modèle de formulaire](./Form-4SF-update.xlsx)
+ [Description du nouveau formulaire](./Form_4SF_update.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/update/4SF/)

## Formulaire 3AA {#3AA}

Pour la déclaration de données sur les [_activités liées aux DCP ancrés_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Activit%C3%A9s_li%C3%A9es_aux_DCP_ancr%C3%A9s).

Le formulaire unifié permet de déclarer simultanément des données pour plusieurs pêcheries :

+ [Modèle de formulaire](./Form-3AA.xlsx)
+ [Description du formulaire](./Form_3AA.html)

Une version du formulaire permet de déclarer des données **mises à jour** pour une seule pêcherie :

+ [Modèle de formulaire](./Form-3AA-update.xlsx)
+ [Description du formulaire](./Form_3AA_update.html)

## Formulaire 3DA{#3DA}

Pour la déclaration de données sur les [_activités liées aux objects flottants dérivants_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Activit%C3%A9s_li%C3%A9es_aux_objects_flottants_d%C3%A9rivants).

Le nouveau formulaire unifié comble les lacunes de l'ancien formulaire 3FA et permet de déclarer des données pour plusieurs navires simultanément :

+ [Modèle de formulaire](./Form-3DA.xlsx)
+ [Description du formulaire](./Form_3DA.html)

Une version du formulaire permet de déclarer des données **mises à jour** pour un seul navire :

+ [Modèle de formulaire](./Form-3DA-update.xlsx)
+ [Description du formulaire](./Form_3DA_update.html)

## Formulaire 3BU {#3BU}

Pour la déclaration de données sur les [_positions journalières des balises_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Positions_journali%C3%A8res_des_balises).

+ [Modèle historique de formulaire](./legacy/Form-)
+ [Nouveau modèle de formulaire](./Form-3BU.xlsx)
+ [Description du nouveau formulaire](./Form_3BU.html)
+ [Validateur interactif du nouveau formulaire](https://data.iotc.org/validators/ui/3BU/)

## Formulaire 2FC {#2FC}

Pour la déclaration de données sur les [_statistiques des bateaux de pêche_](https://data.iotc.org/reference/latest/guidelines/index_fr.html#Statistiques_des_bateaux_de_p%C3%AAche).

+ [Modèle historique de formulaire](./legacy/Form-2FC-legacy.xlsm)
+ [Nouveau modèle de formulaire](./Form-2FC.xlsx)
+ [Description du nouveau formulaire](./Form_2FC.html)

## Form 7PR {#7PR}

Pour la déclaration de données sur les _prix des produits de la pêche pour le thon et les espèces apparentées dans le cadre du mandat de la CTOI_. Le nouveau modèle de formulaire est en cours de construction.

+ [Modèle historique de formulaire](./legacy/Form-7PR-legacy.xlsm)
<!-- + [New form template](./Form-7PR.xlsx) -->
<!-- + [New form description](./Form_7PR.html) -->

